### ISSUE TITLE
部署之后，点击登录报错，后端返回信息如下

### ISSUE THREAD

**Issue by Raoul1996** [tencentyun/wafer2-startup#10]
{"code":-1,"error":"ERR_GET_SESSION_KEY\n{\"code\":5100,\"message\":\"(-1)服务内部错误，请稍后重试或联系客服人员解决。\",\"codeDesc\":\"ResourceOpFailed\"}"}

**Comment by baok1592** [comment]
同问题！腾讯云-系统：小程序PHP sdk镜像系统
三木demo登陆失败！

**Comment by aslinwang** [comment]
也遇到了如下问题
{"code":-1,"error":"ERR_GET_SESSION_KEY\n{"code":5100,"message":"(-1)服务内部错误，请稍后重试或联系客服人员解决。","codeDesc":"ResourceOpFailed"}"}

**Comment by ai19951016** [comment]
我也一样遇到了这个问题
{ “代码”： - 1， “错误”： “ERR_GET_SESSION_KEY \ N {”代码“：5100，”消息“：”（ - 1）服务内部错误，请稍后重试或联系客服人员解决“ ”codeDesc。“： ”ResourceOpFailed“}”

**Comment by jas0ncn** [comment]
你好，点击“登录”提示“(-1) 服务内部错误，请稍后重试或联系客服人员解决。”的错误，可以按照如下方式排查问题：
1. 检查是否将 `client/config.js` 里的 `host` 修改为分配的开发环境域名
2. 重新点击“编译”小程序，点击登录重试
3. 点击“腾讯云”-“重启服务”，重启成功之后点击登录重试
如果以上方法均无法解决，可以将你的腾讯云账号 ID（可以在这查看[https://console.qcloud.com/developer](https://console.qcloud.com/developer)）贴给我，我这里帮您排查一下。

**Comment by jas0ncn** [comment]
你好，点击“登录”提示“(-1) 服务内部错误，请稍后重试或联系客服人员解决。”的错误，可以按照如下方式排查问题：

1. 检查是否将 `client/config.js` 里的 `host` 修改为分配的开发环境域名
2. 重新点击“编译”小程序，点击登录重试
3. 点击“腾讯云”-“重启服务”，重启成功之后点击登录重试
4. 如果你有一定的开发能力，可以启动单步调试，在 `controller/login.js` 里打一下断点，看看具体原因。

如果以上方法均无法解决，可以将你的腾讯云账号 ID（可以在这查看[https://console.qcloud.com/developer](https://console.qcloud.com/developer)）贴给我，我这里帮您排查一下。

**Comment by Raoul1996** [comment]
我的账号ID是： 100001297028，谢谢您的帮助

**Comment by jas0ncn** [comment]
这个问题我们已经排查到了，正在解决。 @Raoul1996 
解决了之后会告知你结果，感谢反馈！

**Comment by jas0ncn** [comment]
问题已经解决了，重启服务，然后点击登录即可成功登录。
@Raoul1996 @aslinwang @ai19951016

**Comment by Raoul1996** [comment]
辛苦了，可是我的问题还存在的。~……~
依旧是一样的错误。
明天我再试试吧。
可能是我配置的有问题吧。

**Comment by jas0ncn** [comment]
@Raoul1996 你需要重启一下服务，或者直接重新部署一下环境

**Comment by Raoul1996** [comment]
嗯嗯，好的

**Comment by Raoul1996** [comment]
重新部署了一次，问题依旧存在。明天再解决吧，真的辛苦了。谢谢你们了。

**Comment by Raoul1996** [comment]
今天我又申请了一个appid，按照教程部署是没有问题，可以登录的。
我对比了一下，昨天我和今天唯一的不同点就是我在`server`下的`config`中对`CONF.appId`进行了配置。今天早上我删掉之后重新上传部署了一下，依旧是登录失败。

**Comment by jas0ncn** [comment]
@Raoul1996 是这样的，`server/config.js` 里有一个 `CONF. useQcloudLogin` 这个默认为 `true`，这样登录不走微信而是走腾讯云代理。如果你想直接用微信，把这个设置为 `false`，然后填上对应的 `CONF. appId ` 和 `CONF. appSecret `。

**Comment by OliverWeb** [comment]
我的账号ID是： 632231327，谢谢您的帮助 @jas0ncn 你好我在做微信小程序用的是wafer2-client-sdk,在调用qcloud.login 返回ERR_GET_SESSION_KEY\n{\"code\":5100,\"message\":\"(-1)服务内部错误，请稍后重试或联系客服人员解决。\",\"codeDesc\":\"ResourceOpFailed\"}",帮忙解决一下
