### ISSUE TITLE
wafer2服务器保存图片如何查看URL地址？

### ISSUE THREAD

**Issue by WPDreamMelody** [tencentyun/wafer2-startup#100]
wafer2服务器download了一个张图，文件流保存到./love.jpeg中，请问网络url是多少？

代码如下：
`if (response.status == 200) {
        //输出返回的内容
        qrcode = response.data;
        fs.writeFile("./love.jpeg", qrcode, "binary", function (err) {
          if (err) {
            console.log("down fail");
          }
          console.log("down success");
        });
      }`

**Comment by jas0ncn** [comment]
你需要引入一个 koa-static 之类的中间件来处理静态文件的请求。然后将文件下载到指定的一个目录下，接着配置这个中间件来处理请求。

Node.js 和 PHP 不一样，不是直接访问文件名就能访问到文件夹下的文件的，这个你可以自行百度。

**Comment by WPDreamMelody** [comment]
感谢 @jas0ncn ，可以了
