### ISSUE TITLE
按照“微信后台如何配置客服消息推送接口”，收到的客服消息为{}

### ISSUE THREAD

**Issue by jackgreentemp** [tencentyun/wafer2-startup#101]
后台调试模式下结果如下，模拟用户在客服消息界面发送消息，腾讯云上的客服消息接口收到该消息

query数据如下
![](https://raw.githubusercontent.com/jackgreentemp/practice/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-01-18%20%E4%B8%8B%E5%8D%8810.20.22.png)

body数据如下，如图body为空对象
![](https://raw.githubusercontent.com/jackgreentemp/practice/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-01-18%20%E4%B8%8B%E5%8D%8810.16.29.png)

**Comment by jas0ncn** [comment]
是的，微信推送过来的消息content-type写成了xml，实际的数据却是json，于是解析失败。需要您自己配置一下bodyparser
