### ISSUE TITLE
图片上传成功，但渲染报错sign check fail

### ISSUE THREAD

**Issue by maxcheers86** [tencentyun/wafer2-startup#103]
图片上传成功了，有图片地址http://wximg-125216****.cosgz.myqcloud.com/1516678212749-HJaHhmVrz.jpg
但渲染时报错sign check fail
本地开发环境，和腾讯云开发环境都报错
{"errorcode":-46618,"errormsg":"sign check fail, retcode:-46618"}
还要开启什么才能访问？

**Comment by maxcheers86** [comment]
生产服务器可以渲染图片，如何在开发服务器也能访问图片？

**Comment by dfang** [comment]
同样碰到这个问题

**Comment by jas0ncn** [comment]
到腾讯云COS控制台，将bucket设置为公有读私有写

**Comment by dfang** [comment]
@jas0ncn bucket不存在，会自动创建的，去看了一下默认就是公有读私有写的啊

**Comment by jas0ncn** [comment]
更新一下新版本的sdk，应该是使用的cos api是老版本的饿
