### ISSUE TITLE
message（客服消息）的content-type需要添加额外判断

### ISSUE THREAD

**Issue by daiqing2009** [tencentyun/wafer2-startup#104]
在koa-bodyparser中是通过hearder中的content-type来判断
虽然根据wiki的说明配置成了json格式，但是微信服务器[接受客服消息和事件](https://mp.weixin.qq.com/debug/wxadoc/dev/api/custommsg/receive.html#%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF%E5%92%8C%E4%BA%8B%E4%BB%B6)接口push的消息header的content-type仍然是“text-xml”

不知道是否还有更合适的提交bug的地方（这是微信服务器的一个bug），先找到这里记录一下。 临时解决代码如下：
`app.use(bodyParser({
      detectJSON: (ctx) => {
        //message强转为json格式,小程序的一个bug：json格式的content-type:"text/xml"
        return /message$/i.test(ctx.path);
    }
}))`

**Comment by jas0ncn** [comment]
我们已经和微信提过这个BUG了，但是由于接口调用量过大，修复可能会导致其他开发者的应用有问题，所以他们暂时没有修复的打算。
我们比较希望您可以自己处理。看起来您已经找到解决办法了~
同时我们也会考虑把这个统一一下~
