### ISSUE TITLE
自行部署安装依赖失败

### ISSUE THREAD

**Issue by superupon** [tencentyun/wafer2-startup#105]
我这边是按照这个教程在腾讯的云服务器上部署Demo的
https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2

但是，在执行到npm install时，安装报错：
![image](https://user-images.githubusercontent.com/7564035/35374824-79b73088-01df-11e8-8526-cd63671e7b07.png)

帮忙看一下什么原因，谢谢

**Comment by superupon** [comment]
[2018-01-25T06_50_30_941Z-debug.log](https://github.com/tencentyun/wafer2-startup/files/1662811/2018-01-25T06_50_30_941Z-debug.log)
这个是具体出错的log文件

**Comment by jas0ncn** [comment]
您可以更换一下npm源哈。
