### ISSUE TITLE
怎么访问数据库表呢？

### ISSUE THREAD

**Issue by ganshenml** [tencentyun/wafer2-startup#106]

**Comment by jas0ncn** [comment]
https://cloud.tencent.com/document/product/619/12794#.E5.A6.82.E4.BD.95.E4.BD.BF.E7.94.A8.E6.9C.8D.E5.8A.A1.E7.AB.AFsdk-.E8.BF.9E.E6.8E.A5.E5.92.8C.E6.93.8D.E4.BD.9C.E6.95.B0.E6.8D.AE.E5.BA.93
文档中有说明哈~

**Comment by ganshenml** [comment]
@jas0ncn 
文档中的案例很简单：
`const { mysql } = qcloud

mysql('db_name').select('*').where({ id: 1 }) // => { id:1, name: 'leo', age: 20 }`

我上传了代码至服务器，但并没有查询到数据（数据库是有数据的）。已经提交了工单。（这块的文档太过简陋了，没有提供一套完整的数据库环境设置、连接、访问的案例。所以，上手起来还是有很多问题。o(╯□╰)o）

**Comment by jas0ncn** [comment]
文档里说明了是使用了 knex，只是做了连接的封装，并没有其他的单独接口，主要的文档就是 knexjs: http://knexjs.org/
