### ISSUE TITLE
部署完成后，显示 This page isn't working

### ISSUE THREAD

**Issue by reynold-Yang** [tencentyun/wafer2-startup#107]
按照教程部署完成后，模拟器一直白屏，最后出现 This page isn't working   控制台报错GET http://127.0.0.1:54783/appservice/appservice net::ERR_EMPTY_RESPONSE   但是用真机测试可以，这是为什么？

**Comment by jas0ncn** [comment]
重启一下开发者工具吧，这个不是 demo 的问题哈

**Comment by reynold-Yang** [comment]
嗯已经重启很多次，并且不适用代理直连网络，发现都不可以。不知道有没有人和我一样的问题？

**Comment by jas0ncn** [comment]
更新一下微信开发者工具呢？
重启需要用任务管理器完全关闭再重启

**Comment by reynold-Yang** [comment]
嗯谢谢  已经确认不是demo的问题了，是我电脑配置问题，但是又找不到具体是哪里配置不对。
