### ISSUE TITLE
无法上传正式代码

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#11]
多次尝试无果，一直卡在 上传中，请等待。。。

**Comment by jas0ncn** [comment]
尝试着在开发者工具的代理设置里，选择使用系统代理试试。

**Comment by SouthernBox** [comment]
是系统代理的，改成不使用代理也不行

**Comment by jas0ncn** [comment]
是使用的最新版的微信开发者工具吗？

**Comment by SouthernBox** [comment]
是的，会不会和生产环境域名未备案有关？

**Comment by jas0ncn** [comment]
不会的。你可以提供一下对应的腾讯云账号ID吗，我这里帮你查一下

**Comment by jas0ncn** [comment]
现在可以了吗？你还可以打开一下开发工具的调试，看看详细返回的信息。可以截图到这里我看一下。

如何打开调试：
<img width="379" alt="a608281c-7300-4ed1-ac5a-05343d917b35" src="https://user-images.githubusercontent.com/3380894/29996118-31011afa-902b-11e7-9e33-8b3cc232ab9e.png">

**Comment by SouthernBox** [comment]
更新到 0901 版开发工具，上传成功了，谢谢！
