### ISSUE TITLE
用小程序做小游戏，后台可以是java环境吗？不用tomcat，用基于java语言的vertx

### ISSUE THREAD

**Issue by CatDogZ** [tencentyun/wafer2-startup#118]
想开发小游戏， 但是不会node.js和php，想用vertx写，也是事件驱动，性能貌似比node.js要好。 我看官网上都推荐的是node.js或php,   请问 不可以用其他语言吗？

**Comment by jas0ncn** [comment]
要是不支持其他语言哈。如果要用java只能自己部署在自己服务器上了
