### ISSUE TITLE
node版本自行部署时候 信道少个接口

### ISSUE THREAD

**Issue by lanbosm** [tencentyun/wafer2-startup#119]
自行部署 信道一直报 没登录态 找了半天 云送的部署没问题 
自己部署少了这个接口 然后返回空的数据  求解
![qq 20180413155724](https://user-images.githubusercontent.com/21954985/38723351-621b388e-3f33-11e8-8408-0d75e47e4845.png)

**Comment by jas0ncn** [comment]
信道服务是腾讯云提供的 Paas 级接口，不需要自行部署。信道是需要先登录然后再带登录态获取信道地址的。
