### ISSUE TITLE
错误10080

### ISSUE THREAD

**Issue by houguang** [tencentyun/wafer2-startup#12]
![qq 20170902102150](https://user-images.githubusercontent.com/1720347/29992208-9f4bf416-8fc8-11e7-88be-048e5cfb68b1.jpg)

![qq 20170902102027](https://user-images.githubusercontent.com/1720347/29992203-87817fae-8fc8-11e7-8b57-3046c65dbf09.jpg)
无法上传

**Comment by Varorbc** [comment]
我也一样，啥情况

**Comment by jas0ncn** [comment]
根目录需要有 project.config.json 文件，检查一下是否有这个文件。
最好使用我们的 Demo 哈。
