### ISSUE TITLE
nodejs 环境 上传图片后cos里有图片,接口报502错误,服务器崩溃

### ISSUE THREAD

**Issue by wenshanshan** [tencentyun/wafer2-startup#121]
服务器为腾讯云的 开发环境
 "wafer-node-sdk": "^1.3.3"
cos的权限设置成"公有读私有写"了
**其他功能正常,上传图片报502.然后所有功能都挂掉,必须要重启node服务器才能恢复**

不知道是什么地方没配置好????折腾一下午了~~~
求解决~~

srv 代码:(demo没改)
module.exports = async ctx => {
    // 获取上传之后的结果
    // 具体可以查看：
    const data = await uploader(ctx.req)
    ctx.state.data = data
}

client代码:(demo没改)
 // 上传图片
        wx.uploadFile({
          url: config.service.uploadUrl,
          filePath: filePath,
          name: 'file',

          success: function (res) {
            util.showSuccess('上传图片成功')
            console.log(res)
            res = JSON.parse(res.data)

            console.log(res)
            that.setData({
              imgUrl: res.data.imgUrl
            })
          },

          fail: function (e) {
            util.showModel('上传图片失败')
          }
        })

**Comment by zhanwen** [comment]
这个应该更新过了，你重新试试，在控制台可以下载node.js的日志看看

**Comment by jas0ncn** [comment]
更新了 SDK 修复了这个问题了，可以恢复开发环境并重新上传代码安装依赖即可。
