### ISSUE TITLE
自行部署文档好坑啊

### ISSUE THREAD

**Issue by empirewarrior** [tencentyun/wafer2-startup#124]
为什么严格按照一步步来的，走了三遍了，到最后一步始终显示502？

**Comment by jas0ncn** [comment]
502 是 Node.js 意外退出了，你看看不是执行 `node app.js` 之后关掉了终端。

**Comment by luisxiaomai** [comment]
@jas0ncn , 有没有自行部署的docker image啊，自己按照文档部署太麻烦了。

**Comment by jas0ncn** [comment]
暂时没有哈
