### ISSUE TITLE
上传腾讯云错误

### ISSUE THREAD

**Issue by wujohns** [tencentyun/wafer2-startup#125]
这里没有用wafer方案，而是采用自己写的测试用的服务端代码：
``` js
'use strict';

const http = require('http');

http.createServer((req, res) => {
    const data = {
        list: [
            { content: '111' },
            { content: '222' }
        ]
    };
    res.end(JSON.stringify(data));
}).listen(5757);
```

同时 package.json 中未配置任何dependencies，上传前重置过腾讯云测试环境，结果上传时出现找不到koa模块（???）,这里调试用的腾讯云服务强制使用koa?

**Comment by wujohns** [comment]
还有就是文档中关于本地调试的配置，你们小程序根本不支持本地的localhost域好不，直接把错误的内容放在文档中坑人不太好吧

**Comment by jas0ncn** [comment]
支持本地运行的，只是本地信道功能不能使用。
你采用自己的代码的话，请直接修改 `app.js` 里面的内容，服务端是直接使用 `node app.js` 命令运行的

**Comment by wujohns** [comment]
wafer（client）的源码中配置为本地访问时，部分请求走wx.request，wx.request是明确不支持本地访问的

**Comment by wujohns** [comment]
还有就是服务端直接执行node app.js这一点也麻烦在文档中说明一下，我这边猜测的时候猜是npm start或node <package.json 中的 main> 怎么也想不到你们是用node app.js这样的套路

**Comment by wujohns** [comment]
已经弃坑了，配置好了https和内网穿透，小程序工具中内置的这个腾讯云工具是真的不能用（完全就是坑时间的）。不过wafer的封装还是很不错的，之后会引入来用。

**Comment by jas0ncn** [comment]
1. 请关闭开发者工具的 TLS 校验，开发时就可以访问本地 localhost。
2. 考虑到 `npm start` 的自定义有风险（例如运行命令或者是使用全局未安装的依赖 pm2 etc.），所以是采用 `node app.js` 运行的。这里是文档没有写清楚，我们这里修改一下。

**Comment by wujohns** [comment]
最终还是跑通了，但是这块最大的问题其实还是在于开发环境的不稳定，上传代码功能是否能正常运作，基本是玄学（同一套代码有时能上传很快直接跑通，有时会卡着完全不能用，挺给腾讯云掉价的）
