### ISSUE TITLE
如何通过sql创建cAuth数据库

### ISSUE THREAD

**Issue by luisxiaomai** [tencentyun/wafer2-startup#129]
现在是手动创建的，我尝试在cAuth.sql里添加``` CREATE DATABASE IF NOT EXISTS xx CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;```再执行```node initdb.js```但是报错。

@jas0ncn 是否有其他的方式可以自动创建cAuth数据库？

**Comment by jas0ncn** [comment]
可以手写 sql 语句哈，不能使用 initdb.js 了。因为 initdb.js 里面使用了 cAuth 数据库
