### ISSUE TITLE
腾讯云入门demo登录失败 

### ISSUE THREAD

**Issue by BraveZhang** [tencentyun/wafer2-startup#13]
![image](https://user-images.githubusercontent.com/25190350/29992220-eb08de5a-8fc8-11e7-93be-ab05797da711.png)
<img width="905" alt="_20170902102717" src="https://user-images.githubusercontent.com/25190350/29992236-5416aeb8-8fc9-11e7-833a-90427af26403.png">

请问是什么原因？

**Comment by jas0ncn** [comment]
这个问题已经发现了。正在修复。
可以使用 wafer2-startup 不会有这个问题。这个主要是精简版有这个问题

**Comment by jas0ncn** [comment]
已经修复啦~请重新 clone 或者下载一下 wafer2-quickstart，并重新部署~
