### ISSUE TITLE
现有的demo是否可以完成数据保存操作？

### ISSUE THREAD

**Issue by aaaaaaaq** [tencentyun/wafer2-startup#130]
demo为node.js的小程序demo。我想通过cgi通过请求到server文件夹下的controllers的文件，然后获取请求参数保存数据库，求教，研究了好几天了一直没进展

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/wafer2-node-sdk/blob/master/lib/mysql/AuthDbService.js#L33
可以参考 sdk 里面的实现。具体可以看 [knex 文档](http://knexjs.org/)
