### ISSUE TITLE
关于数据库性能

### ISSUE THREAD

**Issue by zimo888** [tencentyun/wafer2-startup#133]
请问Mysql 的数据库配置是什么呢，能支持多少连接数，有没有缓存，我们应该如何做数据库的压力测试？

请帮忙解答一下，谢谢。

**Comment by mgsweet** [comment]
@zimo888 自行部署了解一下

**Comment by jas0ncn** [comment]
你好，目前的 MySQL 是搭建在同一台服务器内的，暂时不提供外部直接访问，所以无法进行压力测试。如果你的业务较为庞大，建议自行部署
