### ISSUE TITLE
如何上传音频文件呢

### ISSUE THREAD

**Issue by xenonflash** [tencentyun/wafer2-startup#139]
利用自带的 upload 功能会提示 格式不支持

**Comment by Don107213** [comment]
请问您这个问题解决了吗?我也遇到这个问题了

**Comment by jas0ncn** [comment]
上传音频目前仅支持 mp3 和 m4a 格式：https://github.com/tencentyun/wafer2-node-sdk/blob/master/lib/upload/index.js#L63

**Comment by xenonflash** [comment]
@jas0ncn 嗯, 查看了这里的代码,
