### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by itellboy** [tencentyun/wafer2-startup#14]
![image](https://user-images.githubusercontent.com/17695267/29993807-28d1e080-8ff4-11e7-93b0-7f9644c0bc3f.png)
这是什么原因呢

**Comment by jas0ncn** [comment]
点一下开发者工具右上角的“项目”，看看腾讯云状态里的开发环境，是不是运行中呢？还是已停止。。可以尝试重启一下服务。

**Comment by itellboy** [comment]
![6b _q_ ndt9k 47 2 p 6 r](https://user-images.githubusercontent.com/17695267/29993835-ec52dfbe-8ff4-11e7-9b79-d6b714a00fb4.png)
运行中，但是在我第一次上传代码的时候报了这个错

**Comment by jas0ncn** [comment]
这个报错的话，安装一下依赖。

**Comment by jas0ncn** [comment]
安装完依赖重启服务就行

**Comment by shhuangyan1** [comment]
云服务状态显示停止中，怎么恢复呢

**Comment by jas0ncn** [comment]
重启服务哈~ @shhuangyan1

**Comment by itellboy** [comment]
![image](https://user-images.githubusercontent.com/17695267/29994075-f1d2f352-8ff9-11e7-8024-a0df11406915.png)
安装依赖继续报错，这个权限问题我这边怎么控制呢

**Comment by jas0ncn** [comment]
没有关系哈~这个而是 WARN，如果你觉得有问题，就重新安装一下依赖。。现在其实你可以直接重启了

**Comment by shhuangyan1** [comment]
我登录还是失败 ，云服务器连接上了，但是 调试的回传信息是 {code: 0, data: {}}
code
:
0
data
:
{}

**Comment by itellboy** [comment]
谢谢，我这边重启服务就一直报上面哪个找不到water-node-sdk模块的错误，安装依赖也是如此

**Comment by jas0ncn** [comment]
@shhuangyan1 你用的是精简版的demo吧？更新一下代码，重新部署一下~这里修复了一些bug

**Comment by jas0ncn** [comment]
@itellboy 尝试恢复开发环境，然后重新部署代码试试~

**Comment by itellboy** [comment]
还有个问题，我要吧appid和secret也一起配置到config.js里面去吗？我看到readme里面有这一步，但是文件里面是有这一项的

**Comment by jas0ncn** [comment]
`server/config.js` 里有一个 `CONF.useQcloudLogin` 这个默认为 `true`，这样登录不走微信而是走腾讯云代理。如果你想直接用微信，把这个设置为 `false`，然后填上对应的 `CONF.appId` 和 `CONF.appSecret`。

**Comment by itellboy** [comment]
恢复开发环境还是一样，上传测试代码，重启服务都报上面一样的错误，找不到模块。安装依赖就报那个警告

**Comment by itellboy** [comment]
。。刚刚请了浏览器cookie缓存重新登录了一下，突然就行了，很奇怪为什么会出来这样的问题

**Comment by jas0ncn** [comment]
🤣好的，OK了就好。。是清除了微信开发者工具的 cookie 吗？

**Comment by itellboy** [comment]
0.0你这个表情哪来的，是的

**Comment by jas0ncn** [comment]
好的，我这里测试一下。。
哈哈表情打出来的
