### ISSUE TITLE
腾讯云微信小程序新版DEMO登录授权失败

### ISSUE THREAD

**Issue by limol** [tencentyun/wafer2-startup#142]
下载了新版的DEMO，据说是根据小程序更改登录授权窗口后做出相应调整的新的腾讯云登录DEMO
改成自身分配的服务器相关的域名和账号密码等后，就出现了以下错误，网络上没有任何的资料，也不知道哪里出了问题，想问一下如何解决

Error: 响应错误，{"code":0,"data":{}}
    at Function.success (login.js? [sm]:84)
    at Object.success (WAService.js:3)
    at s.<anonymous> (WAService.js:10)
    at s.emit (WAService.js:4)
    at Function.<anonymous> (WAService.js:10)
    at WAService.js:4
    at a (VM1339 appservice:1008)
    at b.<anonymous> (VM1339 appservice:1008)
    at b.emit (VM1339 appservice:1008)
    at callback (VM1339 appservice:1008)
console.error @ VM1334:1
fail @ index.js? [sm]:87
success @ login.js? [sm]:84
(anonymous) @ WAService.js:3
(anonymous) @ WAService.js:10
s.emit @ WAService.js:4
(anonymous) @ WAService.js:10
(anonymous) @ WAService.js:4
a @ VM1339 appservice:1008
(anonymous) @ VM1339 appservice:1008
b.emit @ VM1339 appservice:1008
callback @ VM1339 appservice:1008
setTimeout @ VM1339 appservice:1008
(anonymous) @ WAService.js:3
(anonymous) @ WAService.js:8
setTimeout (async)
setTimeout @ WAService.js:8
h @ VM1339 appservice:1008
c @ VM1339 appservice:1008
d @ VM1339 appservice:1008
b.emit @ VM1339 appservice:1008
window.setSecurityDetails @ VM1339 appservice:1008
(anonymous) @ VM1366:1

**Comment by jas0ncn** [comment]
前端请求的 URL 是否正确呢？提供一下  host

**Comment by limol** [comment]
![_20180614234924](https://user-images.githubusercontent.com/38974875/41423453-f76df43c-702d-11e8-8d61-2613081c58de.jpg)
![1528991509](https://user-images.githubusercontent.com/38974875/41423458-f87e9eb2-702d-11e8-9d15-65b8fbf1df00.jpg)
麻烦帮忙看下，辛苦啦~

**Comment by jas0ncn** [comment]
如果你填了生产环境域名就要部署到生产环境，你这个域名看起来应该是开发环境

**Comment by jas0ncn** [comment]
另外是做什么操作的时候报的这个错误？

**Comment by limol** [comment]
在执行登录操作的时候呀，另外我现在更改了域名为生产环境域名的时候，就弹出这个错误了。。。
login.js? [sm]:81 {code: -1, error: "ERR_WHEN_INSERT_TO_DB↵Error: ER_ACCESS_DENIED_ERRO…for user 'root'@'localhost' (using password: YES)"}code: -1error: "ERR_WHEN_INSERT_TO_DB↵Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)"__proto__: Object
VM283:1 Error: 响应错误，{"code":-1,"error":"ERR_WHEN_INSERT_TO_DB\nError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)"}
    at Function.success (login.js? [sm]:83)
    at Object.success (WAService.js:3)
    at s.<anonymous> (WAService.js:10)
    at s.emit (WAService.js:4)
    at Function.<anonymous> (WAService.js:10)
    at WAService.js:4
    at a (VM288 appservice:1013)
    at b.<anonymous> (VM288 appservice:1013)
    at b.emit (VM288 appservice:1013)
    at callback (VM288 appservice:1013)

**Comment by limol** [comment]
我也上传了正式代码，也进行了代码部署，但还是出现了响应错误，第一次是code是0，第二次是code是-1，有点懵

**Comment by jas0ncn** [comment]
这个错误是 MySQL 数据库密码输入错误了

**Comment by limol** [comment]
请问，腾讯云的登录是只能使用生产环境域名的phpMyAdmin吗，不能使用开发环境的phpMyAdmin吗？

**Comment by limol** [comment]
问题解决啦，谢谢小哥哥
