### ISSUE TITLE
图片上传到cos成功，但图片没有文件名，只有后缀

### ISSUE THREAD

**Issue by JamesHT** [tencentyun/wafer2-startup#145]
相关版本信息：
"name": "qcloud-weapp-client-demo","version": "2.0.0",
"wafer-node-sdk": "^1.4.1"
"wafer2-client-sdk": "^2.1.0"

返回结果：
<img width="775" alt="2018-06-29 10 29 07" src="https://user-images.githubusercontent.com/749535/42070109-876c736a-7b87-11e8-9363-3fbc96f64903.png">

<img width="1165" alt="2018-06-29 10 32 08" src="https://user-images.githubusercontent.com/749535/42070166-b9a79e40-7b87-11e8-84dd-f6f6d8bf1dd7.png">

**Comment by jas0ncn** [comment]
已修复，https://github.com/tencentyun/wafer2-node-sdk/commit/d4bf5b0f30756c112c445a741808a55363b4efe8

**Comment by jas0ncn** [comment]
请更新 wafer-node-sdk 到 1.4.5 修复！
