### ISSUE TITLE
路由和mysql

### ISSUE THREAD

**Issue by zxd696** [tencentyun/wafer2-startup#149]
就是想问问，node后台可以用express模块写接口， mysql模块连接处理数据库么？

**Comment by jas0ncn** [comment]
可以的。启动文件是 `app.js`

**Comment by Jennival** [comment]
您好，请教一下：如果我想要小程序连接MySQL的话，我是不是要用node.js写接口，然后在小程序中访问接口，就可以实现小程序与数据库的连通了？

**Comment by jas0ncn** [comment]
@Jennival 是的
