### ISSUE TITLE
错误：10080

### ISSUE THREAD

**Issue by googlegis** [tencentyun/wafer2-startup#15]
Error: 未找到 project.config.json 中的 svr 字段。 错误：10080

按照操作步骤，上传测试代码时，提示该错误。请问该如何解决？

**Comment by jas0ncn** [comment]
选择的是wafer2-startup的根目录吗？不要选择client目录。。截图一下你的微信开发者工具里的项目结构我看看。

**Comment by googlegis** [comment]
确实目录选择问题，选择根目录即可上传成功。因为教程中的图片是 client 目录，所以认为是要选择 client 目录。现在已经上传成功。多谢。

**Comment by jas0ncn** [comment]
教程中哪个截图，可以提供一下截图吗？我这里核实一下。。
