### ISSUE TITLE
咨询费用问题

### ISSUE THREAD

**Issue by deepsolo9** [tencentyun/wafer2-startup#150]
在控制台看到了，请忽略。不过还是把[wiki](https://github.com/tencentyun/wafer2-startup/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E5%92%8C%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83)里面生产环境的免费使用给去掉吧，要不然容易引起误解。

**Comment by jas0ncn** [comment]
已经修改，感谢提醒！
