### ISSUE TITLE
小程序访问储存桶

### ISSUE THREAD

**Issue by Jennival** [tencentyun/wafer2-startup#151]
微信小程序访问腾讯云储存桶中的.doc文件，小程序中无法显示，但是链接在浏览器中能打开，显示错误原因是errMsg: "openDocument:fail filetype not supported"，可是小程序访问tomcat中的.doc文件就没有问题，并且小程序访问储存桶中的其他文件（图片、视频、ppt）也没有问题，请问问题在哪儿啊？

**Comment by jas0ncn** [comment]
这个是微信小程序的问题哈，不是我们 Wafer2 解决方案的，我也不是特别的清楚。你可以到 https://developers.weixin.qq.com/ 提问一下
