### ISSUE TITLE
startup默认配置下登录失败

### ISSUE THREAD

**Issue by yidazh** [tencentyun/wafer2-startup#153]
照着README（#c0fb3b3）一步一步来，部署成功后测试登录，登录失败提示err_get_session_key。

经查发现默认配置已启用useQcloudLogin，但是又没提示要配置qcloudSecretId和qcloudSecretKey。关闭useQcloudLogin并填入appSecret重新部署后，可以正常登录。

建议完善相关默认配置和文档。第一次玩小程序，还没开始就采坑。。。

**Comment by jas0ncn** [comment]
qcloudSecretId 和 qcloudSecretKey 是环境默认提供，如果你腾讯云绑定的小程序和开发时创建项目的小程序不一样，就会报错。
