### ISSUE TITLE
自行部署使用nodejs什么版本的？大于7.6的都可以吗？

### ISSUE THREAD

**Issue by lkls004** [tencentyun/wafer2-startup#154]
目前自行部署wafer2-quickstart，登录提示5100，使用的是腾讯云服务器和云数据库，发起
https://wss.api.qcloud.com/v2/index.php?Action=GetSessionKey&js_code=011dlymZ1NTKj11LNGnZ1qaomZ1dlymL&Timestamp=1533202489&Nonce=6821734&SecretId=AKIDc3GEwOQYFgrmSrQway61h7ICrGOGnGND&SignatureMethod=HmacSHA256&Signature=xyEbLb7AIgZXAnR5XGQIq3rI90eIrdmIQEobqdXCxOo%3D 会返回ERR_GET_SESSION_KEY: { code: 5100,message: '(-1)服务内部错误，请稍后重试或联系客服人员解决。',codeDesc: 'ResourceOpFailed' } node -v 8.4.0

**Comment by jas0ncn** [comment]
server/config.js 上填上 AppID 和 AppSecret，然后将 useQcloudLogin 设置为 false
