### ISSUE TITLE
希望小程序开发工具支持ubuntu 

### ISSUE THREAD

**Issue by jk0011** [tencentyun/wafer2-startup#155]
希望小程序开发工具支持ubuntu

**Comment by jas0ncn** [comment]
支持 ubuntu 是什么意思呢？具体怎么个支持法？

**Comment by liujianspace** [comment]
目前开发工具只有windows版和mac版

**Comment by jas0ncn** [comment]
小程序开发者工具是微信那边开发的哈，可以到 https://developers.weixin.qq.com/ 提一下问题
