### ISSUE TITLE
部署到腾讯云的生成环境问题

### ISSUE THREAD

**Issue by xanhf** [tencentyun/wafer2-startup#156]
我使用开发环境登陆是没有问题的，部署到生成环境时候，登录老提示先试用login登录后调用缓存登录请问这是为什么

**Comment by jas0ncn** [comment]
清除一下本地缓存，如果是手机端则先把小程序删除再测试。https://github.com/tencentyun/wafer2-startup/blob/master/client/pages/index/index.js#L63
