### ISSUE TITLE
wafer的登录问题

### ISSUE THREAD

**Issue by deepsolo9** [tencentyun/wafer2-startup#157]
请问wafer的设计里面，是否是如果需要登录的话一定需要用户授权？如果没有授权而只是使用wx.login的code来进行登录的话，在服务端wafer-node-sdk里面auth/index.js的41行会报错找不到user_info，也就是session表里面还没有相关条目。

跟踪了一下代码，saveUserInfo只有在用户授权了得到encryptedData和iv以后才会进行，那么请问wafer的整个生态是否有一个前提是必须得到用户的授权，仅仅wx.login是不行的？

**Comment by jas0ncn** [comment]
是的，仅仅使用 wx.login 登录确实不支持，仅支持非首次登录使用 wx.login

**Comment by deepsolo9** [comment]
不知道为何这样设计，微信社区里面官方的回答都是建议开发者在不需要得到用户授权的情况下来设计产品的账号体系，因为在wx.login的情况下，整个账号体系的回路已经可以建立起来了，并不是一定需要昵称和头像。且其实wafer-node-sdk想支持的话很简单，我目前自己是简单改了一下auth/index.js文件就达到目标了，目前还没有发现是否有其他影响。
