### ISSUE TITLE
生产环境上传图片地址只有.png或者.jpg

### ISSUE THREAD

**Issue by LYnnProspery** [tencentyun/wafer2-startup#158]
测试环境ok，上传图片后返回一个xxx/xxx.jpg的图片。生产环境返回为xxx/.jpg路径。如何区分图片地址？

**Comment by jas0ncn** [comment]
上传的文件名不要包含文件夹，如果需要上传到指定文件夹，可以使用 config 中的 cos.fileBucket 配置项：https://github.com/tencentyun/wafer2-node-sdk/blob/master/API.md
