### ISSUE TITLE
生产环境上传图片报code-1

### ISSUE THREAD

**Issue by funky-tiger** [tencentyun/wafer2-startup#163]
用的wafer2的upload接口 开发环境可以正常上传并返回地址  更改config中的host为生产环境后就报错
{code: -1, error: "ERR_REQUEST_LOST_FIELD"}
缺少字段？ip不在白名单？
网上搜不到 不知所云 求告知 谢谢！

**Comment by jas0ncn** [comment]
这是因为上传的时候有个 field 字段，是否修改了 config.js 的 config.cos.fieldName 这个字段呢？如果修改了需要修改会 file，或者和前端的上传 field 对应的

https://github.com/tencentyun/wafer2-node-sdk/blob/d4bf5b0f30756c112c445a741808a55363b4efe8/lib/upload/index.js#L56

**Comment by funky-tiger** [comment]
您好 我仔细排查了你说的fieldName字段 发现我 config.js 中并没有cos.fieldName字段  并且在前端也并没有发现field字段？这分别是后端和前端的截图：
---后端------前端---


------------------ 原始邮件 ------------------
发件人: "Jason Chen"<notifications@github.com>;
发送时间: 2018年9月3日(星期一) 下午4:47
收件人: "tencentyun/wafer2-startup"<wafer2-startup@noreply.github.com>;
抄送: "NoFlexZone"<764427188@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [tencentyun/wafer2-startup] 生产环境上传图片报code-1 (#163)




这是因为上传的时候有个 field 字段，是否修改了 config.js 的 config.cos.fieldName 这个字段呢？如果修改了需要修改会 file，或者和前端的上传 field 对应的
 
https://github.com/tencentyun/wafer2-node-sdk/blob/d4bf5b0f30756c112c445a741808a55363b4efe8/lib/upload/index.js#L56

**Comment by funky-tiger** [comment]
您好 我仔细排查了你说的fieldName字段 发现我 config.js 中并没有cos.fieldName字段  并且在前端也并没有发现field字段？
后端：
cos: {
        /**
         * 区域
         * @查看 https://cloud.tencent.com/document/product/436/6224
         */
      region: 'ap-shanghai',
        // Bucket 名称
        fileBucket: 'cir_product',
        // 文件夹
        uploadFolder: ''
    },

**Comment by funky-tiger** [comment]
我发现我没有动config.js里面的cos的任何东西 就是不好使 就是报错{code: -1, error: "ERR_REQUEST_LOST_FIELD"}
不懂 好迷好迷

**Comment by funky-tiger** [comment]
后端server：
    cos: {
        region: 'ap-guangzhou',

        fileBucket: 'qcloudtest',

        uploadFolder: '',
    }
前端：
{
      url: config.service.uploadUrl,
      filePath: this.state.imgFilePath[i],
       name: 'file'
}
此时报错变成：
{code: -1, error: "[object Object]"}

**Comment by funky-tiger** [comment]
问题解决 记录一下：
如果是{code: -1, error: "ERR_REQUEST_LOST_FIELD"}就按照上面的说法去做
如果是{code: -1, error: "[object Object]"} 就是因为wafer2默认的存储桶和所属地域的问题 
更改一下server/config/cos.region和fileBucket就好了
我的cos的所属地域是华南 这样写即可解决：
cos: {
      region: 'cn-south',
        // Bucket 名称
      fileBucket: 'qcloudtest',
        // 文件夹
      uploadFolder: '',
    },
