### ISSUE TITLE
含有emoji的昵称无法上传到mySQL？

### ISSUE THREAD

**Issue by xrlu0929** [tencentyun/wafer2-startup#171]
我把所有地方都设好了utf8mb4，结果每次用户昵称里，只要有emoji就报错，完全上传不上来。。。报错信息：
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x90\x9F' for column 'nickName' at row 1"
求助。。谢谢

**Comment by jas0ncn** [comment]
连接数据库的时候要设置 charset 为 utf8mb4
