### ISSUE TITLE
信道发生错误

### ISSUE THREAD

**Issue by a0215cpl** [tencentyun/wafer2-startup#172]
code:1001
detail:RequestError
    message:"登录态已过期"
    type:"Request failed with status code 404"
message:"连接信道服务失败，网络错误或者信道服务没有正确响应"
-----------------------------------------------------------------------------------------------
"Error
    at http://127.0.0.1:18645/appservice/vendor/wafer2-client-sdk/lib/request.js:33:30
    at http://127.0.0.1:18645/appservice/vendor/wafer2-client-sdk/lib/request.js:37:2
    at require (http://127.0.0.1:18645/appservice/__dev__/WAService.js:1:699587)
    at http://127.0.0.1:18645/appservice/__dev__/WAService.js:1:699196
    at http://127.0.0.1:18645/appservice/vendor/wafer2-client-sdk/index.js:6:15
    at require (http://127.0.0.1:18645/appservice/__dev__/WAService.js:1:699587)
    at http://127.0.0.1:18645/appservice/__dev__/WAService.js:1:699196
    at http://127.0.0.1:18645/appservice/app.js:7:14
    at require (http://127.0.0.1:18645/appservice/__dev__/WAService.js:1:699587)
    at <anonymous>:1:1"
-----------------------------------------------------------------------------------------------
其他登陆,请求,上传图片都是成功的。

**Comment by herochen** [comment]
遇到一样的问题。查看代码，信道连接的时候，需要调用wafer_node-sdk/lib/tunnel/api.js 中的这个函数。
requestConnect (receiveUrl) {
        const protocolType = 'wss'
        const param = { receiveUrl, protocolType }
        return this._sendRequest('/get/wsurl', param, true)
    },
发现需要往/get/wsurl发送请求。应该也是在这里报了404的错误。现在不确定/get/wsurl这个处理程序是不是需要自己实现才行，又或者需要部署另外一个包含这个url处理的程序

**Comment by jas0ncn** [comment]
已经修复！
