### ISSUE TITLE
信道服务器404错误

### ISSUE THREAD

**Issue by RLee063** [tencentyun/wafer2-startup#174]
1. 今天信道服务器突然发生错误，尝试连接就会报错：“连接信道服务失败，网络错误或者信道服务没有正确响应”
2. 如何搭建自己的信道服务器

**Comment by herochen** [comment]
遇到一样的问题。查看代码，信道连接的时候，需要调用wafer_node-sdk/lib/tunnel/api.js 中的这个函数。
requestConnect (receiveUrl) {
const protocolType = 'wss'
const param = { receiveUrl, protocolType }
return this._sendRequest('/get/wsurl', param, true)
},
发现需要往/get/wsurl发送请求。应该也是在这里报了404的错误。现在不确定/get/wsurl这个处理程序是不是需要自己实现才行，又或者需要部署另外一个包含这个url处理的程序

**Comment by RLee063** [comment]
> 遇到一样的问题。查看代码，信道连接的时候，需要调用wafer_node-sdk/lib/tunnel/api.js 中的这个函数。
> requestConnect (receiveUrl) {
> const protocolType = 'wss'
> const param = { receiveUrl, protocolType }
> return this._sendRequest('/get/wsurl', param, true)
> },
> 发现需要往/get/wsurl发送请求。应该也是在这里报了404的错误。现在不确定/get/wsurl这个处理程序是不是需要自己实现才行，又或者需要部署另外一个包含这个url处理的程序

信道服务器以前由腾讯云免费提供，现在不维护了，需要自己搭建信道服务器，也就是你说的部署另外一个包含这个url处理的程序

**Comment by herochen** [comment]
> > 遇到一样的问题。查看代码，信道连接的时候，需要调用wafer_node-sdk/lib/tunnel/api.js 中的这个函数。
> > requestConnect (receiveUrl) {
> > const protocolType = 'wss'
> > const param = { receiveUrl, protocolType }
> > return this._sendRequest('/get/wsurl', param, true)
> > },
> > 发现需要往/get/wsurl发送请求。应该也是在这里报了404的错误。现在不确定/get/wsurl这个处理程序是不是需要自己实现才行，又或者需要部署另外一个包含这个url处理的程序
> 
> 信道服务器以前由腾讯云免费提供，现在不维护了，需要自己搭建信道服务器，也就是你说的部署另外一个包含这个url处理的程序

原来如此。谢谢

**Comment by jas0ncn** [comment]
已经修复，但是依然建议自行搭建
