### ISSUE TITLE
上传测试代码出错

### ISSUE THREAD

**Issue by Mo2Tec** [tencentyun/wafer2-startup#18]
提示：
{"code":-1,"reason":"module.js:487\n throw err;\n ^\n\nError: Cannot find module 'wafer-node-sdk'\n at Function.Module._resolveFilename (module.js:485:15)\n at Function.Module._load (module.js:437:25)\n at Module."}
（都是按教程操作的）

**Comment by jas0ncn** [comment]
点击右上角腾讯云，选择安装依赖，安装依赖完成以后选择重启服务。
