### ISSUE TITLE
Mysql提供多大的容量？

### ISSUE THREAD

**Issue by Varorbc** [tencentyun/wafer2-startup#19]
![_20170904141159](https://user-images.githubusercontent.com/5714438/30013788-196a809c-917b-11e7-9204-e791317d9a51.png)
请问开发环境和正式环境下的Mysql分别提供多大的免费容量？？？？

**Comment by jas0ncn** [comment]
开发环境的数据库是在服务器里的，目前是有 50G 的云硬盘。
生产环境使用的云数据库是 10G 的，未来将会提供更多可以选定的配置
