### ISSUE TITLE
获取用户缓存数据代码错误

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#20]
在客户端 SDK 中，登录获取用户数据缓存，成功获取后的代码为：
options.success(session.userInfo);
大小写有误，应为：
options.success(session.userinfo);

**Comment by jas0ncn** [comment]
已修改

**Comment by SouthernBox** [comment]
目测改错地方了。。。

**Comment by jas0ncn** [comment]
噗。。看到了。。。又改了一下

**Comment by SouthernBox** [comment]
存的时候存是 Session.set(res.skey);
是不是应该改成 Session.set(res);
