### ISSUE TITLE
建议将登录和获取用户信息的逻辑区分开

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#21]
调用 wx.login 后就已经可以实现登录逻辑了，并不一定要 getUserInfo，现在微信也不建议这样做。
另一个弊端是，当用户拒绝授权后，微信不会再弹框提示，也就是无法再登录。
建议修改 SDK 中的登录方法，保证不会弹窗，再增加一个更新用户信息的方法，将何时需要获取用户信息交给开发者判断。

**Comment by jas0ncn** [comment]
好的，这个问题我们会评估一下解决。

**Comment by jas0ncn** [comment]
我这里思考了一下。
你说的这个问题不需要修改 sdk，如果要只实现登录，不获取信息，直接用 `wx.login` 就行了，没必要使用 sdk 来登录。
至于更新用户信息，可以写一个接口手动更新数据库，我们是有暴露 MySQL 实例的。

**Comment by SouthernBox** [comment]
1. 需要评估的不是「不修改 sdk 能不能实现这个功能」，而是「目前的 sdk 登录方法是否具有普遍的适用性」；
2. 理论上所有的功能都可以不通过 sdk 实现，这是怎样做更合理更方便的问题；
3. 可以试想一下，直接使用了这个 sdk 的小程序，基本都是一打开就弹框要授权，这是目前微信不提倡的，可能会无法通过审核；
4. 依然没有考虑拒绝授权的情况，拒绝授权 sdk 抛出「请检查网络状态」；
5. 当然，以上都是个人建议。 我也可以自己写接口，或者修改 sdk 实现。

参考：http://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=c45683ebfa39ce8fe71def0631fad26b

**Comment by XiaoChenYung** [comment]
我也是同样的问题，如果SDK还是没有修改把获取用户信息分开，我也只能弃用SDK的功能了，所有逻辑都靠自己实现

**Comment by jas0ncn** [comment]
已经实现，可以参考：https://github.com/tencentyun/wafer2-quickstart/issues/10
