### ISSUE TITLE
腾讯云-上传测试代码

### ISSUE THREAD

**Issue by smalldew** [tencentyun/wafer2-startup#24]
腾讯云-上传测试代码-模块上传

勾选 
上传node_modules以外代码

勾选 
上传node_modules代码

提示
Error:未找到project.cofig.json 中的svr字段。 错误10080

**Comment by jas0ncn** [comment]
要选择 wafer2-startup 的根目录，而不是 client 目录哈~

**Comment by jas0ncn** [comment]
![default](https://user-images.githubusercontent.com/3380894/30051997-a090f124-9256-11e7-8edd-300058572ee5.png)
