### ISSUE TITLE
是否考虑锁依赖版本

### ISSUE THREAD

**Issue by everywill** [tencentyun/wafer2-startup#27]

**Comment by jas0ncn** [comment]
wafer2-startup 依赖的包都遵循了 [semver 2.0](http://semver.org/) 版本号规范，可以无需锁版本号。如果你觉得对版本安装不信任，可以手动 lock 版本或者使用 npm 自动创建 `package-lock.json` 文件，上传代码之后，服务端会根据 `package-lock.json` 安装依赖。
