### ISSUE TITLE
编译后无法正常访问页面

### ISSUE THREAD

**Issue by timtimwen** [tencentyun/wafer2-startup#28]
* 背景：同一个微信账户，在两台电脑上开发同一份代码
* 问题：在第一台电脑部署后，编译运行正常。在第二台电脑上编译后，自动跳转的页面报错，无法正常访问，报错信息如下图：

![2017-09-07 10 48 24](https://user-images.githubusercontent.com/8698041/30144014-44d87da0-93bb-11e7-9687-af3b3db35ddf.png)

**Comment by jas0ncn** [comment]
这个应该是微信开发者工具的问题，你可以尝试更新一下最新版：[https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html](https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html)

另外如果开了代理软件，请关闭全局代理，并将开发者工具里面的代理设置设置为不使用代理

**Comment by timtimwen** [comment]
@jas0ncn Done, thx..
