### ISSUE TITLE
上传测试代码总是提示超时

### ISSUE THREAD

**Issue by myfdeveloper** [tencentyun/wafer2-startup#29]
上传测试代码总是提示超时，提示框 “环境部署中，请等待”，过一段时间后提示“{"code":-1,"reason":"任务超时"}”

**Comment by jas0ncn** [comment]
是首次上传测试代码吗？能否提供一下腾讯云的账号 ID 给我一下，我这里帮您查一下。
可以在 [https://console.qcloud.com/developer](https://console.qcloud.com/developer) 查询账号 ID

**Comment by YvanMao** [comment]
是的首次上传
100001342856

**Comment by xcchcaptain** [comment]
首次上传
100001360181
遇到同样的问题

**Comment by littlexk** [comment]
首次上传，也遇到同样的问题。  100001360004

**Comment by poxlee** [comment]
无法访问此网站

无法找到 aboutblank 的 DNS 地址。正在诊断该问题。
DNS_PROBE_POSSIBLE


GET http://1303106673.appservice.open.weixin.qq.com/appservice net::ERR_NAME_NOT_RESOLVED

**Comment by jas0ncn** [comment]
@poxlee 检查一下是否开启了代理，如果开启了代理，不要选择全局代理。并关闭微信开发者工具的代理设置。

**Comment by poxlee** [comment]
已经解决,感谢大神帮助

**Comment by jas0ncn** [comment]
这里请大家再重新尝试上传一下代码即可，我们修复了一些 BUG
