### ISSUE TITLE
上传代码 总是出现错误

### ISSUE THREAD

**Issue by qiaorancho** [tencentyun/wafer2-startup#30]
编辑器提示：
{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}

**Comment by jas0ncn** [comment]
能否提供一下腾讯云的账号 ID 给我一下，我这里帮您查一下。
可以在 [https://console.qcloud.com/developer](https://console.qcloud.com/developer) 查询账号 ID

**Comment by qiaorancho** [comment]
我已经把我的信息发到您的邮箱 me@ijason.cc  里面了：
请您查看 @jas0ncn 

谢谢您

**Comment by qiaorancho** [comment]
今天上传突然好了，我知道怎么回事。 我尝试过更新微信开发工具的版本

**Comment by jas0ncn** [comment]
这边是帮你处理了一下。

**Comment by zhuobinggang** [comment]
我也出现了这个问题，如果有解决方案应该贴出来吧。 @jas0ncn  ，我也发了封邮件，麻烦处理下

**Comment by jas0ncn** [comment]
要先点击上传测试代码，才能点击其他的重启之类的操作。

**Comment by arcelan** [comment]
同样出现这个问题，报同样的错，{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}，
就是在上传测试代码的时候报错的，腾讯云的账号 ID已邮件发送 @jas0ncn

**Comment by jas0ncn** [comment]
您好，值班工程师已经处理了，逐步恢复了，重试即可。
