### ISSUE TITLE
配置本地开发环境报错，

### ISSUE THREAD

**Issue by ZhangEryi** [tencentyun/wafer2-startup#31]
![e2](https://user-images.githubusercontent.com/26322447/30155703-18613d22-93f0-11e7-8d09-b034b50f2170.jpg)
![e1](https://user-images.githubusercontent.com/26322447/30155704-1862bf30-93f0-11e7-8dc0-eeb3527cff60.jpg)
无论是npm run dev  还是run start  都报错 看着应该是同一个错误  求解答，每次改代码都上传服务器测试太麻烦啦

**Comment by jas0ncn** [comment]
截图里的错误信息乱码了。。能否使用 vs code 里面的终端启动尝试一下，截图看看输出了什么。。。这样不大好定位问题。

另外方便问一下你机子上的 Node.js 版本号是多少？

**Comment by ZhangEryi** [comment]
![qq 20170907214655](https://user-images.githubusercontent.com/26322447/30166506-1dde0a0c-9416-11e7-9fb0-ec98a26866a9.png)
![44](https://user-images.githubusercontent.com/26322447/30167180-2695ed16-9418-11e7-8eb6-98d255bf696b.png)


试了两台电脑 一个是 8.4.0  一个是6.6.0  都报错 

8.4.0 的话直接node app.js 可以运行    6.6.0 node app.js 应该是报不支持async错

另外本地环境我把数据库的host改成了被分配的域名 
但是连接不上 用sqlfront 也连接不上  不知道为什么 万分感谢

![2](https://user-images.githubusercontent.com/26322447/30167204-3c18797e-9418-11e7-98ca-85bc3fbf8bad.png)

**Comment by jas0ncn** [comment]
要使用 8.4 的 Node.js。
尝试将 `nodemon.json` 里的 `"node --harmony"` 改成 `"node"` 试试。
本地要使用 `npm run local-dev` 来运行。
数据库的问题是，host 不能带有 `https://`，直接填写后面的二级域名就行

**Comment by ZhangEryi** [comment]
您好 我按你说的 把node --harmony 改成了 node  运行 npm run local-dev 提示script中未定义  也确实是没有这个
我运行npm run dev 可以了 也监听文件改变了  感谢！
但是数据库我直接用二级域名 一直提示访问超时 
我用phpmyadmin  把用户 root 的localhost 改成%  或者新加用户 用%  都链接不上提示超时  不知道什么原因  
![n2](https://user-images.githubusercontent.com/26322447/30193333-19e6e356-947f-11e7-95f0-53cade30ef44.jpg)
![n1](https://user-images.githubusercontent.com/26322447/30193334-19e88a94-947f-11e7-97b4-05359ea5cda1.jpg)

**Comment by jas0ncn** [comment]
改成ip试一下~

**Comment by ZhangEryi** [comment]
还是不行 提示超时

**Comment by jas0ncn** [comment]
我这里咨询了一下后端的配置，是安全组没有放开 3306 端口。建议你在本地搭建 MySQL 数据库来测试。

**Comment by ZhangEryi** [comment]
哦哦 好的 谢谢！ 建议在文档中修复下 以免更多人遇到我同样的问题哈

**Comment by jas0ncn** [comment]
好的！感谢反馈

**Comment by ZhangEryi** [comment]
![o5](https://user-images.githubusercontent.com/26322447/30204720-0bae3fca-94b9-11e7-842d-f24fb53ed1a4.jpg)
![o3](https://user-images.githubusercontent.com/26322447/30204482-33d70154-94b8-11e7-8b93-562b1cf80726.jpg)
![o2](https://user-images.githubusercontent.com/26322447/30204483-33dc157c-94b8-11e7-8ef5-c3ebe662a3f5.jpg)
您好，我用本地数据库也出现问题了，如图所示 knex 提示数据库链接不上  然而我直接用mysql 不通过knex的话就可以连上数据库输出数据  试了把localhost改成127或者本地ip192  问题依然存在

我在另一个项目中 用sequelize 连接同一个数据库测试没问题 
非常奇怪
