### ISSUE TITLE
用本地数据库也出现问题了 囧~~

### ISSUE THREAD

**Issue by ZhangEryi** [tencentyun/wafer2-startup#32]
![o5](https://user-images.githubusercontent.com/26322447/30204837-7aff6714-94b9-11e7-940e-c693f5d4f610.jpg)
![o3](https://user-images.githubusercontent.com/26322447/30204840-7ba9d47e-94b9-11e7-9a74-d103d1f14a18.jpg)
![o2](https://user-images.githubusercontent.com/26322447/30204838-7aff9d56-94b9-11e7-9aa3-1b291310935a.jpg)

您好，我用本地数据库也出现问题了，如图所示 knex 提示数据库链接不上 然而我直接用mysql 不通过knex的话就可以连上数据库输出数据 试了把localhost改成127或者本地ip192 问题依然存在
![o1](https://user-images.githubusercontent.com/26322447/30204914-b9a8dcca-94b9-11e7-842c-7cc57eb2236d.jpg)

我在另一个项目中 用sequelize 连接同一个数据库测试没问题
非常奇怪

**Comment by ZhangEryi** [comment]
找到原因了，是不是这个端口只能用默认端口3306？   我换成另一个数据库是默认端口 3306可以了

**Comment by jas0ncn** [comment]
这个取决于配置吧。不清楚你具体配置情况。。不过可以了就好
