### ISSUE TITLE
发现wafer-node-sdk下mysql配置未传port的端口设置，导致数据库非3306端口链接不上

### ISSUE THREAD

**Issue by ZhangEryi** [tencentyun/wafer2-startup#33]
![image](https://user-images.githubusercontent.com/26322447/30256509-f0726e76-96dd-11e7-8275-0ca0daa0a862.png)
在配置本地开发环境时，如图。发现wafer-node-sdk下mysql配置未传port的端口设置，在项目中用了别的端口，结果数据库依然使用默认端口进行链接，导致链接不上。给后面小伙伴提个醒哈

**Comment by jas0ncn** [comment]
这个已经修复了哈~更新最新版的 SDK 就行。
https://github.com/tencentyun/wafer2-node-sdk/commit/2f75a1c259430bfb01c3e3e5ae7dc26a3c186e4e
