### ISSUE TITLE
上传文件大小是否有限制？

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#34]
请问上传的文件大小是否有限制？发现上传稍大一点的文件（10 MB），就会一直卡在上传中。

**Comment by SouthernBox** [comment]
开发版上传成功了，正式版又一直卡在上传中，跟文件大小没有关系。
无法上传的问题该好好整一下了，失败了好歹也给点反馈。
目前应该还没有人能把这个方案用在正式项目中。

**Comment by jas0ncn** [comment]
你可以打开一下开发者工具里的调试：
![image](https://user-images.githubusercontent.com/3380894/30305012-2ddff5e2-97a3-11e7-91f4-5ca9ecea42d4.png)
看看是否有返回上传地址。
或者更换一下 DNS 试试。

**Comment by SouthernBox** [comment]
又上传成功了。。。
