### ISSUE TITLE
一站式部署是否一定要使用MySQL

### ISSUE THREAD

**Issue by codermango** [tencentyun/wafer2-startup#35]
请问如果要是用新版开发工具的一站式部署，是否一定要使用这个demo的文件结构和MySQL和cos的配置，我自己本身的项目很小，不需要配置这些，是不是就只能自行部署？

谢谢。

**Comment by jas0ncn** [comment]
不需要哈~如果你不使用我们的 SDK 和 Demo，就无需使用相同的 MySQL 结构，你可以自行上腾讯云控制台，进入 PHPMyAdmin 来修改 MySQL 结构

**Comment by codermango** [comment]
👍
