### ISSUE TITLE
生产环境的默认数据库用户名是什么

### ISSUE THREAD

**Issue by dev-itsheng** [tencentyun/wafer2-startup#37]
你好，请问一下微信小程序开发者工具方案中的生产环境数据库默认用户名是什么

因为在腾讯云后台生产环境的 phpMyAdmin 用 root 用户名和短信发过来的密码无法登陆，但是在「修改密码」里面可以修改（修改密码不需要填写用户名），所以用户名并不是 root

**Comment by yuhong220002** [comment]
root
和
appid

**Comment by jas0ncn** [comment]
@dev-itsheng 是 root 和短信里的密码哈。如果不是可以提供一下账号 ID 我们看看。要注意云数据库的 ip 在 phpMyAdmin 查看，并且只能通过你的服务器来访问的，是内网 IP，有外网隔离，本地无法直接连接

**Comment by dev-itsheng** [comment]
我用的就是 root 和短信里的密码

1. 用 phpMyAdmin 登录不上去

![1](https://user-images.githubusercontent.com/10683193/30357462-4e434f72-9871-11e7-9f9c-5ee0ef8ac4c3.png)


2. 使用微信开发者工具上传正式代码并部署之后，请求接口仍然报数据库登录不上去的错误

![2](https://user-images.githubusercontent.com/10683193/30357467-55022342-9871-11e7-9dee-9e6518b45e5d.png)

3. 在腾讯云后台使用「重置密码」功能时，填这个原密码可以正常修改，但这里不需要填写登录用户名

![3](https://user-images.githubusercontent.com/10683193/30357572-f1fe614c-9871-11e7-963d-8a415bd60515.png)

所以我最开始还怀疑是不是用户名到底是不是 root………………

**Comment by jas0ncn** [comment]
确认是生产环境吗？这里可以提供一下你的腾讯云账号 ID，我们这里帮你排查一下问题~
可以在 https://console.qcloud.com/developer 查询账号 ID

**Comment by dev-itsheng** [comment]
确认是生产环境

账号 ID 为 100001350433

感谢

**Comment by yuhong220002** [comment]
ID:100001396810
同问
root不能登陆

**Comment by yuhong220002** [comment]
解决了吗

**Comment by sokewoniu** [comment]
ID:100001351689
同问

**Comment by jas0ncn** [comment]
已经解决了。使用 `root` 账号及短信发送的 MySQL 密码重新登录即可。

**Comment by sokewoniu** [comment]
ID:100001351689
问题依旧存在，不知您所说的解决了是怎么解决的？
