### ISSUE TITLE
请问生产环境如何配置

### ISSUE THREAD

**Issue by yuhong220002** [tencentyun/wafer2-startup#38]
开发环境已经说的很清楚了
但是生产环境的流程没有介绍

现在ping我自己生产环境的域名会返回负载均衡ip，网页访问域名会404
而网页访问开发环境域名会返回data

生产环境的sdk是如何部署的？

**Comment by jas0ncn** [comment]
生产环境是差不多的，通过 IDE 来上传代码。然后在腾讯云后台进行部署~

**Comment by yuhong220002** [comment]
@jas0ncn 请问小程序包文件具体是运行在哪里的呢，比如我上传了我的小程序，那小程序应该在微信里面的，为什么我还要把小程序包上传到云服务器呢

**Comment by jas0ncn** [comment]
是这样的，小程序分成两个部分的，简单来说，就类似前后端分离的网页。前端就是小程序，是上传到微信的，用户使用的时候会下载下来运行在微信上。而后端就是开发者自己提供的接口，这部分是需要一个云服务器来运行的。目前我们提供了一个 Node.js 的云环境，用户直接上传代码即可运行。

**Comment by yuhong220002** [comment]
![Uploading 7b643f541060f7ea1bd19725ad9e17d.png…]()

请问我打开微信开发者工具，生产环境中 写着 云服务状态停止中....
我已经上传了正式代码...

**Comment by jas0ncn** [comment]
是的，那只是上传。上传之后需要到[腾讯云微信小程序控制台](https://console.qcloud.com/lav2/production)里进行部署：
![生产环境](https://user-images.githubusercontent.com/3380894/30364421-c134a40c-9896-11e7-9920-e524b3b17909.png)

**Comment by yuhong220002** [comment]
我已经部署下去了，还是这样的。。。

**Comment by jas0ncn** [comment]
部署成功了吗？
方便提供一下你的腾讯云账号 ID，我这里帮您查询一下。

**Comment by yuhong220002** [comment]
：  注册账号 
：  gh_1b8b1a3d4462 关联账号 
：  -账号ID 
：  100001375464

**Comment by yuhong220002** [comment]
感谢

**Comment by yuhong220002** [comment]
还有，点了生产环境数据库 直接出apache的 404
![image](https://user-images.githubusercontent.com/11711788/30365821-81ab7d56-989b-11e7-9f33-c8f9ccb05034.png)

**Comment by jas0ncn** [comment]
现在还会吗？

**Comment by yuhong220002** [comment]
我是解析出现了问题，这个问题解决了，非常感谢
