### ISSUE TITLE
服务端 sdk 更新用户信息代码有误

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#39]
服务端 sdk 保存用户信息代码：

// 如果存在用户则更新
if (res[0].hasUser) {
    return mysql('cSessionInfo').update({
         uuid, skey, create_time, last_visit_time, session_key, user_info
    })
} 

麻烦加个 where ，好不容易迁移过来的数据，瞬间全部被覆盖。。。

**Comment by jas0ncn** [comment]
这个是个问题。。马上解决

**Comment by jas0ncn** [comment]
已修复，更新 `wafer-node-sdk` 到 1.0.7 版本即可：
```bash
npm i wafer-node-sdk@1.0.7 -S
```
