### ISSUE TITLE
wafer2用了几台主机

### ISSUE THREAD

**Issue by yuhong220002** [tencentyun/wafer2-startup#42]
wafer用了1个业务主机 1个会话主机  一个负载均衡  一个数据库
wafer2是不是只用了一个业务主机？

**Comment by jas0ncn** [comment]
是的

**Comment by yuhong220002** [comment]
那我续费的时候是不是  只续费一个业务主机即可！！！！

**Comment by yuhong220002** [comment]
在续费一个数据库    那个负载均衡和会话主机不用管了吧

**Comment by jas0ncn** [comment]
wafer2 是免费的哈

**Comment by yuhong220002** [comment]
我知道wafer2是免费的提供demo和sdk， 生产环境的正式代码不是部署在我自己的主机上吗？

**Comment by jas0ncn** [comment]
不是的。以后会提供选择，不过目前暂时是我们分配的环境

**Comment by yuhong220002** [comment]
..那我用生产环境让程序跑起来了，不会出现问题吧- -

**Comment by yuhong220002** [comment]
毕竟好多人用呢。

**Comment by yuhong220002** [comment]
怎么可以让这个生产环境变成自己的？

**Comment by yuhong220002** [comment]
我自己买主机和数据库

**Comment by jas0ncn** [comment]
你可以自行部署到自己的主机上。有相关的文档：https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2

**Comment by yuhong220002** [comment]
非常感谢
