### ISSUE TITLE
生产环境数据库问题，

### ISSUE THREAD

**Issue by yuhong220002** [tencentyun/wafer2-startup#43]
phpMyAdmin 用帐号密码可以登陆

但是wafer2的里运行的时候提示数据库帐号密码有问题

用的是腾讯云自己提供的生产环境  （开发环境没问题）

![screenshot_20170915-113212](https://user-images.githubusercontent.com/11711788/30465493-0881d46e-9a0a-11e7-9a35-c048bcd8afb4.png)

**Comment by yuhong220002** [comment]
问题解决了，需要自己进服务端把 数据库的主机地址改一下，默认是localhost不管用，登陆phpmyadmin看数据库的内网地址。

**Comment by jas0ncn** [comment]
是的。

**Comment by yuhong220002** [comment]
建议说明一下，咱们给了一套开发环境部署的说明， 生产环境没有说明如何部署

**Comment by sokewoniu** [comment]
ID:100001351689
phpmyadmin依旧登录不了
默认密码已经修改过了

**Comment by jas0ncn** [comment]
@sokewoniu 方便截图一下错误提示吗？
