### ISSUE TITLE
自行部署安装依赖报错

### ISSUE THREAD

**Issue by yuhong220002** [tencentyun/wafer2-startup#44]
![image](https://user-images.githubusercontent.com/11711788/30486187-48cfc6ea-9a62-11e7-8567-47b801bf76f0.png)
如图

**Comment by yuhong220002** [comment]
是不是包有问题

**Comment by yuhong220002** [comment]
这个安不上，进域名是502  进/login也是502 不会返回数据

**Comment by yuhong220002** [comment]
求解，很着急

**Comment by yuhong220002** [comment]
依赖安装上了，依然502
![image](https://user-images.githubusercontent.com/11711788/30490754-8009e086-9a6d-11e7-92eb-15e6b1045e39.png)

**Comment by yuhong220002** [comment]
[error (1).zip](https://github.com/tencentyun/wafer2-startup/files/1306899/error.1.zip)
nginx打印的错误报告

**Comment by yuhong220002** [comment]
看23点40以后的就好

**Comment by yuhong220002** [comment]
在自己电脑里可以按上依赖，
在云服务器里就不行。

**Comment by yuhong220002** [comment]
![image](https://user-images.githubusercontent.com/11711788/30509562-0a3a7f9a-9ae6-11e7-9d35-d2610043de02.png)

**Comment by yuhong220002** [comment]
启不动

**Comment by yuhong220002** [comment]
server一直没启来，所以nginx不知道转发给谁报502，求问什么问题。

**Comment by jas0ncn** [comment]
Node.js 进程没有启动。检查一下错误日志：
```bash
pm2 logs app
```

**Comment by yuhong220002** [comment]
![image](https://user-images.githubusercontent.com/11711788/30509815-a1a2bb4a-9aeb-11e7-8a5b-e30b31c36aa8.png)

**Comment by yuhong220002** [comment]
很着急，求教

**Comment by jas0ncn** [comment]
你上传的代码有改动什么吗？

**Comment by jas0ncn** [comment]
这里是报你代码里面缺少了配置项，，

**Comment by yuhong220002** [comment]
什么都没有改动，下的是最新的版本，改的都是数据库帐号，密码，id这些东西。

**Comment by yuhong220002** [comment]
用的是这个教程：https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2

**Comment by jas0ncn** [comment]
```js
    serverHost: '你的域名',
    tunnelServerUrl: 'http://tunnel.ws.qcloud.la',
    tunnelSignatureKey: '27fb7d1c161b7ca52d73cce0f1d833f9f5b5ec89',
  	// 腾讯云相关配置可以查看云 API 秘钥控制台：https://console.qcloud.com/capi
    qcloudAppId: '你的腾讯云 AppID',
    qcloudSecretId: '你的腾讯云 SecretId',
    qcloudSecretKey: '你的腾讯云 SecretKey',
    wxMessageToken: 'weixinmsgtoken',
    networkTimeout: 30000
```

这部分是否有加上？

**Comment by yuhong220002** [comment]
教程里这些配置在一个文件
最新版的在俩文件
![image](https://user-images.githubusercontent.com/11711788/30509887-f71e1dac-9aec-11e7-954b-f0173b5a0284.png)

**Comment by yuhong220002** [comment]
![image](https://user-images.githubusercontent.com/11711788/30509888-085966da-9aed-11e7-9aae-b2080111e763.png)

**Comment by jas0ncn** [comment]
不。`config.local.js.example` 是本地的。自行部署还是一样的。

**Comment by jas0ncn** [comment]
不要发有秘钥的截图。防止被别人盗用。

**Comment by yuhong220002** [comment]
非常感谢   有反馈了{"code":0,"data":{}}

下载的包里config没有下面这些，建议加上。



   serverHost: '你的域名',
    tunnelServerUrl: 'http://tunnel.ws.qcloud.la',
    tunnelSignatureKey: '27fb7d1c161b7ca52d73cce0f1d833f9f5b5ec89',
  	// 腾讯云相关配置可以查看云 API 秘钥控制台：https://console.qcloud.com/capi
    qcloudAppId: '你的腾讯云 AppID',
    qcloudSecretId: '你的腾讯云 SecretId',
    qcloudSecretKey: '你的腾讯云 SecretKey',
    wxMessageToken: 'weixinmsgtoken',
    networkTimeout: 30000

**Comment by jas0ncn** [comment]
不能加上，只有自行部署需要这些配置。一站式部署已经自动下发到机器上。

另外你需要访问 `/weapp/login` 才是登录地址。你可以打开 `routes/index.js` 将最上面的：
```js
const router = require('koa-router')({
    prefix: '/weapp'   // 定义所有路由的前缀都已 /weapp 开头
})
```
改为
```js
const router = require('koa-router')()
```
这样就是 `/login` 了。

**Comment by yuhong220002** [comment]
非常感谢，

建议还是加上文档说明

现在自行部署用的包是 一键部署的包，里面有很多区别

但是没有说明

**Comment by yuhong220002** [comment]
如果把server的router按照上面改了

 client的这块也要改
![image](https://user-images.githubusercontent.com/11711788/30510310-53b649f2-9af4-11e7-9732-4f2a367b70f6.png)

**Comment by jas0ncn** [comment]
有说明的。。完全按照那个文档做就可以了。

**Comment by jas0ncn** [comment]
是的。
