### ISSUE TITLE
生产环境phamyadmin无法登录

### ISSUE THREAD

**Issue by sokewoniu** [tencentyun/wafer2-startup#45]
账号ID:100001351689
生产环境phpmyadmin无法登录，错误如下图：

![default](https://user-images.githubusercontent.com/31379784/30487198-555c821a-9a65-11e7-9cd6-3040b70197a2.png)

**Comment by yuhong220002** [comment]
去腾讯云上提交工单

**Comment by sokewoniu** [comment]
好的，多谢

**Comment by jas0ncn** [comment]
好的，下午帮您看看

**Comment by jas0ncn** [comment]
已帮您解决了，重新登录尝试一下~

**Comment by sokewoniu** [comment]
多谢，已经可以登录！
