### ISSUE TITLE
使用一站式部署如何备案

### ISSUE THREAD

**Issue by dev-itsheng** [tencentyun/wafer2-startup#46]
根据微信小程序要求，相关的服务器域名必须备案，但是在腾讯云提交备案的时候，由于没有购买服务器，无法选择云服务，也就无法继续操作。

请问这个问题如何解决。

![1](https://user-images.githubusercontent.com/10683193/30520901-fa2cc80c-9be8-11e7-8f9a-d71d7fec489d.jpg)

**Comment by jas0ncn** [comment]
目前还不能使用小程序生产环境的机器来备案哈，我们之后将支持这个能力。目前你只能新购一个机器来备案。

**Comment by dev-itsheng** [comment]
1. 能不能给一个大概的时间，什么时候能支持……

2. 备案相关的问题我也给腾讯云提了工单，他们帮我查到了域名自动解析到的 IP 地址 119.29.158.xxx 在 帐号1000009528** 下，根据 Wiki 「腾讯云提供开发和生产两套环境」来看，这个账号应该是你们控制的，需要用这个账号登录，生成一下备案授权码发过来就可以备案了，不知道你们有没有这个权限……

3. 如果上面第二条做不到，我新购买一个云服务器的话，是否需要将域名对应的 IP 地址改到这个云服务器上才能进行备案，然后等备完案再改回来……

**Comment by jas0ncn** [comment]
1. 目前暂时还没有办法给到时间期限，因为这个需要排期
2. 因为实际上小程序解决方案只提供运行环境，所以暂时不能直接帮你生成一个备案授权码，十分抱歉！
3. 你可以新购一个云服务器，只需要将域名的 `www` 记录和 `@` 记录解析到新购的云服务器就行，不需要修改小程序这边的配置。因为我们默认帮你解析了一个随机的二级域名，普通操作不删除该记录的话并不会影响到小程序的使用。
