### ISSUE TITLE
client/lib/login的一个小bug

### ISSUE THREAD

**Issue by everywill** [tencentyun/wafer2-startup#47]
在doLogin里set session时并没有把userInfo信息存进去，因此在checkSession时即使成功也是无法通过getStorage获取userInfo信息的.

**Comment by jas0ncn** [comment]
这个部分稍后会修改并支持。目前可以拉去 `/user` 接口获取信息

**Comment by sokewoniu** [comment]
![default](https://user-images.githubusercontent.com/31379784/30529562-35b7fb5c-9c71-11e7-8b6b-da4331f50961.png)
![default](https://user-images.githubusercontent.com/31379784/30529580-4e60c918-9c71-11e7-8c8d-33e25ad494e5.png)
可以先自己改动这两处，凑合使用
