### ISSUE TITLE
快速新建路由失败

### ISSUE THREAD

**Issue by duz-sg** [tencentyun/wafer2-startup#48]
根据文档建立了新的路由demo，内容完全copy自文档内容。
两个问题：
1. 腾讯云里面并没有“部署开发环境”按钮
<img width="292" alt="screen shot 2017-09-20 at 2 14 23 am" src="https://user-images.githubusercontent.com/12764936/30608136-f51d4860-9da9-11e7-9cba-5ac9ebe56069.png">
2. 测试结果在 webapp/demo 中只有 
`{"code":0,"data":{}}`
并没有预期的 hello world

**Comment by jas0ncn** [comment]
因为开发者工具更新了，只需要点击上传测试代码即可。您测试一下重新上传测试代码试试。

**Comment by duz-sg** [comment]
对的，测试代码有上传，安装依赖，重启服务，恢复开发环境都试过。还有从头检查了config中的参数，但是浏览器返回结果还是 {"code":0,"data":{}}， 似乎是默认返回结果。

**Comment by jas0ncn** [comment]
您可以按照一下几步排查一下：
- 访问的是 `/weapp/demo` 吗？
- 检查一下 `server/routes/index.js` 里面第一行有否：
  ```javascript
     const router = require('koa-router')({
        prefix: '/weapp'
     })
  ```
  如果没有可以补上，或者直接访问 `/demo`

如果都无法解决，可以提供您的腾讯云账号 ID 给我一下，我帮您排查。

**Comment by duz-sg** [comment]
解决了，是typo，写成 webapp 了。
谢谢
