### ISSUE TITLE
能出一个完全空的DEMO吗？去掉所有示例代码，或者出一个清除示例代码的方法，谢谢。

### ISSUE THREAD

**Issue by showeriszero** [tencentyun/wafer2-startup#49]
如题！

**Comment by jas0ncn** [comment]
不大明白您的意思？您可以自己删除代码哦

**Comment by showeriszero** [comment]
嗯，初学者怕删多了没发运行了，如果没有空的框架，能指导一下把哪些文件和内容删了，可以把demo本身的功能全去除掉。DEMO是一个聊天的，我可能需要的是一个用户管理的应用。

**Comment by jas0ncn** [comment]
您可以把 `controllers` 里面的除 `index.js` 全部删除，然后将 `routes/index.js` 里面的所有 `router.xxx` 开头的都删掉即可。
