### ISSUE TITLE
上传代码完成之后仍显示未开通开发环境

### ISSUE THREAD

**Issue by ShawnZhong** [tencentyun/wafer2-startup#5]
显示上传成功：
![image](https://user-images.githubusercontent.com/6421097/29508047-9a8ac786-8618-11e7-9d14-d32f1f49396c.png)
腾讯云状态：
![image](https://user-images.githubusercontent.com/6421097/29508057-a62e47b6-8618-11e7-9c28-b8515a7046e0.png)
小程序授权：
![image](https://user-images.githubusercontent.com/6421097/29508066-b304f4da-8618-11e7-9dab-15b648960697.png)

**Comment by jas0ncn** [comment]
要部署开发环境之后才会同步腾讯云状态

**Comment by unforesndprson** [comment]
部署开发环境任务超时。

**Comment by jas0ncn** [comment]
部署开发环境超时的问题我们已经关注到了，正在解决。
