### ISSUE TITLE
使用客户端SDK调用 /login , /user 报错

### ISSUE THREAD

**Issue by YouthBaby** [tencentyun/wafer2-startup#50]
使用客户端SDK调用 /login , /user 报错 ERR_SKEY_INVALID 登录态过期 ,但是在 服务端 controllers.login 方法里 ctx.state.$wxInfo 可以获取到 用户的信息，但是小程序里一直报错，验证也一直有问题，用qcloud.login()
成功回调里可以拿到userinfo,但是qcloud.request({  url: xxx.qcloud.la/login 或者/user  }) 就拿不到userinfo

**Comment by jas0ncn** [comment]
如果没有修改过 `routes`，默认的路径应该是 `/weapp/login` 而不是 `/login`，检查一下是否是这个问题呢？

**Comment by YouthBaby** [comment]
感谢大佬，已经解决了，是客户端SDK的问题，看到有个小伙伴说客户端SDK有点bug, session.set()方法传了 
res,最后改回来res.skey就好了，之前服务端middleware里那个bodyParser好像有点问题，删了就好了，不删一直报错
