### ISSUE TITLE
上传测试代码到腾讯云，提示：-80072，通知腾讯云发生错误

### ISSUE THREAD

**Issue by jinghang** [tencentyun/wafer2-startup#52]
上传测试代码到腾讯云，提示：-80072，通知腾讯云发生错误
![image](https://user-images.githubusercontent.com/3844686/30897041-b35f0188-a386-11e7-88b3-161fb68f2ed1.png)

是按照教程一步一步往下走，
已经在小程序后台开通了腾讯云
![image](https://user-images.githubusercontent.com/3844686/30900024-f9d0a38e-a394-11e7-8ade-85b67b4f6324.png)

**Comment by viperasi** [comment]
相同错误。

**Comment by dingo826** [comment]
也遇到同个问题，求解

**Comment by jas0ncn** [comment]
这个问题已经修复了。重试即可哈
