### ISSUE TITLE
readme 建议加上修改生产环境数据库host和密码的方法

### ISSUE THREAD

**Issue by GuoliangWang** [tencentyun/wafer2-startup#53]
先在腾讯云管理后台生产环境phpmyadmin里查看 数据库host(类似服务器： 172.x.x.x via TCP/IP的字样)
server端config.js mysql的host由localhost修改成云数据库的ip: 172.x.x.x  密码为登录phpmyadmin的密码

**Comment by jas0ncn** [comment]
这个我们马上加上。

**Comment by HakChealKim** [comment]
没太搞懂，问的什么！

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/qcloud-documents/blob/master/product/%E7%A7%BB%E5%8A%A8%E4%B8%8E%E9%80%9A%E4%BF%A1/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E6%96%B9%E6%A1%88/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B/%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2.md

文档更新在这里了，官网上的在等待审核更新。
