### ISSUE TITLE
退出聊天室后再进入，可能会报错

### ISSUE THREAD

**Issue by SouthernBox** [tencentyun/wafer2-startup#54]
当退出聊天室后马上再进入，可能会报错，多次退出进入很好复现：
![](https://user-images.githubusercontent.com/17867304/30956168-ef5206ee-a468-11e7-8577-9648c7f656ad.png)
可能是在信道未关闭的时候将其再打开导致的。之后就一直无法连接了。

请问如何有效避免该问题？另外，能否区分不同聊天室？

**Comment by jas0ncn** [comment]
这个是微信开发者工具的问题吧。你可以到微信开发者社区问一问。

**Comment by SouthernBox** [comment]
这跟开发工具没关系吧，错误是 sdk 报的，三木聊天室就有这个问题。

**Comment by jas0ncn** [comment]
这确实就是因为信道没有关闭，可能是小程序意外退出了，这种情况下 SDK 是没有办法主动关闭信道了，因为程序里面的信息已经丢失了。。应该重新编译可以解决问题。

**Comment by SouthernBox** [comment]
真机也会的，考虑改成一进入小程序就连接信道。
另外，请问能否区分不同聊天室？

**Comment by jas0ncn** [comment]
连接信道是需要登录态的，一进小程序就连接不太现实，不过你可以自己实现。

区分聊天室是可以的，你可以直接修改 server 端的代码，通过新增标志位来区分聊天室

**Comment by jas0ncn** [comment]
至于马上进入信道冲突的话，可以设置一个标志位，当信道未关闭的时候先不要连接。

**Comment by SouthernBox** [comment]
是不是消息同样会发给所有人，然后根据消息里的标志位判断是哪个聊天室？

这个错误是在 new qcloud.Tunnel(config.service.tunnelUrl) 的时候报的，获取不到 tunnel 就无法进行后续操作了。

**Comment by jas0ncn** [comment]
不是的，信道 ID 和聊天室你要在服务端维持一个映射，只推送给需要接收到数据的人。
不需要修改 SDK，你只需要在外层判断一下。

**Comment by SouthernBox** [comment]
感谢你的详细解答！
我后端不太熟悉，请问需要修改服务端哪个文件？

**Comment by jas0ncn** [comment]
修改 `controllers/tunnel.js`

**Comment by SouthernBox** [comment]
我研究一下。再次感谢！

**Comment by SouthernBox** [comment]
如果发现信道未关闭，不要抛错，改成 console.log()，正常返回 tunnel。
这样会不会合理一些？

**Comment by jas0ncn** [comment]
这样是不行的，错误不处理怎么可以呢？你可以自己修改一下 SDK。但是我这里不能统一修改成这个样子。

**Comment by SouthernBox** [comment]
我认为这个错误应该在调用 open 的时候抛

**Comment by jas0ncn** [comment]
前面说了，这个是开发者工具丢出来的错误，只是 SDK 接到了接着丢出来而已，并没有办法规定他要在什么时候丢出来这个错误

**Comment by SouthernBox** [comment]
应该不是工具问题，真机也有。试想网络环境不好的情况下，还没有连接上就退出了，再次进入就会出现。

我自己改吧。

**Comment by jas0ncn** [comment]
你没有理解我的意思。我说的不是开发者工具的问题，而是只要连接信道就会返回错误。这个错误是开发者工具返回的（真机就是微信返回的）。我们没有办法规定什么时候出现错误。

**Comment by SouthernBox** [comment]
获取 tunnel 的时候不报错，在调用 open 之前先判断是否已经连接，这样就能保证代码正常跑了。

**Comment by jas0ncn** [comment]
那只能您自己修改这个SDK了，我们这里没有办法统一的修改这个。您可以看一下源码来了解一下我们的实现。对于 `currentTunnel` 的校验部分。

**Comment by SouthernBox** [comment]
好的，感谢耐心解答。
