### ISSUE TITLE
本地开发环境 websocket 连接报错

### ISSUE THREAD

**Issue by YvanMao** [tencentyun/wafer2-startup#56]
本地有办法调试websocket服务吗？要怎么设置？

request:fail invalid url "localhost:5757/weapp/tunnel"

信道发生错误： {code: 1001, message: "连接信道服务失败，网络错误或者信道服务没有正确响应", detail: {…}}

**Comment by YvanMao** [comment]
看到说明目前本地开发环境不支持websocket，只支持测试和生产环境，或者部署自己的服务

**Comment by jas0ncn** [comment]
本地肯定是不支持的。因为信道服务如果收到消息需要通知你的程序，你的程序在本地，无法通知到的。
