### ISSUE TITLE
 上传代码 总是出现错误6001

### ISSUE THREAD

**Issue by mlpy** [tencentyun/wafer2-startup#58]
你好, 我上传测试代码时, 总是提示如下错误:
{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}.
腾讯云账号已发送您的邮箱me@ijason.cc 
麻烦您抽时间处理一下这个问题, 万分感谢!!

**Comment by mrpclass** [comment]
metoo;mrp@tianzhong.com.cn

**Comment by jas0ncn** [comment]
您好，值班工程师已经处理了，逐步恢复了，重试即可。
