### ISSUE TITLE
上传测试代码总是提示6001,希望得到解决

### ISSUE THREAD

**Issue by rusice97** [tencentyun/wafer2-startup#59]
![l w a wj i_ps eh m](https://user-images.githubusercontent.com/27399715/31311851-ae2ab23e-abe7-11e7-8993-b71c98b68c27.png)
开发工具上传测试代码,重置开发环境都是返回!

> {"code":-1,"reason":"6001:主机未找到或者不在您账户下

腾讯云ID:
账号id 1746706862
appid 1251101557

**Comment by jas0ncn** [comment]
您好，值班工程师已经处理了，逐步恢复了，重试即可！
