### ISSUE TITLE
对 wafer 和 wafer2 选择的一点疑问

### ISSUE THREAD

**Issue by YvanMao** [tencentyun/wafer2-startup#61]
wafer 和 wafer2是不是不同的解决方案？还是说wafer2最终将取代wafer？

wafer2提供免费的生产环境和开发环境，那是不是不需要再购买腾讯云的业务服务器了？那wafer购买的业务和会话服务器是不是就用不上了？

**Comment by ystarlongzi** [comment]
wafer2 的生成环境不是免费的，还是要掏钱买服务的

**Comment by jas0ncn** [comment]
Wafer 和 Wafer2 最终将会合并，提供多个套餐，不过我们还在努力开发，暂时会同时存在。
就目前来说，采用 Wafer2 就是免费的生产环境和开发环境，但是仅仅只有运行环境，如果你想要更灵活的控制 CVM，就可以购买 Wafer
