### ISSUE TITLE
上传测试代码 报错

### ISSUE THREAD

**Issue by HakChealKim** [tencentyun/wafer2-startup#64]
clone code  上传代码到腾讯云 就 挂掉
提示 如下： 
{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}
什么原因呢？ 有人遇到过吗？
注册账号：gh_0a0e63426374(微信公众平台账号)
账号ID：100001993231
希望  高手指点！！！

**Comment by jas0ncn** [comment]
这边查询您已经成功了是吗？

**Comment by ramseyjiang** [comment]
上传测试代码报错，打开demo也报错。已反馈给微信同事，但是目前还无回复。求解决
<img width="934" alt="screen shot 2017-10-16 at 12 12 57" src="https://user-images.githubusercontent.com/6574141/31594979-ec15936c-b294-11e7-933a-4f1fa796309d.png">

**Comment by ramseyjiang** [comment]
下图是上传测试代码的报错
<img width="419" alt="screen shot 2017-10-16 at 12 15 44" src="https://user-images.githubusercontent.com/6574141/31594997-14d25876-b295-11e7-8d7b-7ed30ac3a848.png">

**Comment by jas0ncn** [comment]
@ramseyjiang  这个是微信更新了开发者工具所导致的，已经修复了兼容问题，重新下载代码替换原来的即可。
