### ISSUE TITLE
按Readme文档操作，报错了一下。

### ISSUE THREAD

**Issue by firevenus** [tencentyun/wafer2-startup#66]
错误提示如下：

Error: 未找到 project.config.json 中的 qcloudRoot 字段。错误：10080

根据的是这个文档进行操作的：

​https://github.com/tencentyun/wafer2-startup

不知道是不是权限的问题， 感觉文档还可以再写的细一点。

**Comment by jas0ncn** [comment]
这个是微信更新了开发者工具所导致的，已经修复了兼容问题，重新下载代码替换原来的即可。
