### ISSUE TITLE
knex连接mysql部分；

### ISSUE THREAD

**Issue by HakChealKim** [tencentyun/wafer2-startup#67]
knex连接mysql，自己尝试着写了一下，老是失败，建议是否可以给个demo，or example？

**Comment by jas0ncn** [comment]
SDK 已经连接好了。导出就可以直接操作了：
```javascript
const { mysql } = qcloud
mysql('db_name').select('*').where({ id: 1 }) // => { id:1, name: 'leo', age: 20 }
```

**Comment by HakChealKim** [comment]
我在server/controller下写了db.js
const { mysql } = require('../qcloud')
module.exports = async ctx => {
  var res = await mysql('cAppinfo').select('*').where({session_duration : 2000}).first()
  ctx.state.data = res
}
root的index下加了个路由；
但是res结果是空，后来在尝试nginx就502了；。。。。
appid：100001993231

**Comment by HakChealKim** [comment]
最新错误 日志：

{"code":-1,"reason":"/data/release/node-weapp-demo/node_modules/koa-router/lib/layer.js:38 throw new Error( ^ Error: get `/db`: `middleware` must be a function, not `undefined` at Layer.<anonymous> (/data/release/node-wea"}

**Comment by jas0ncn** [comment]
路由要写在routes/index.js

**Comment by HakChealKim** [comment]
server/routes/index.js下：
router.get('/db', controllers.db.get)
可是 不 work

**Comment by HakChealKim** [comment]
为了方便查看 把初始代码放到了github：
https://github.com/HakChealKim/goal_project

**Comment by jas0ncn** [comment]
router.get('/db', controllers.db)

没有 .get 这个方法

**Comment by HakChealKim** [comment]
嗯，好的，下班回去试试；
谢谢

**Comment by HakChealKim** [comment]
我发现 root cause 可能不是mysql连接问题，
最简单的api调用后，返回的结果都有问题的；如附件[](url)
<img width="1483" alt="screen shot 2017-10-20 at 6 20 40 pm" src="https://user-images.githubusercontent.com/9987586/31816948-d97bb5f4-b557-11e7-9cf2-fc60d0f5e276.png">
