### ISSUE TITLE
微信小程序如何关闭腾讯云&授权？

### ISSUE THREAD

**Issue by zhe-he** [tencentyun/wafer2-startup#68]
在小程序里面的设置->开发者工具->腾讯云，当点击了开通之后，我没找到关闭的地方，请问如何关闭？？？

**Comment by jas0ncn** [comment]
您可以到微信小程序后台，取消腾讯云的授权。
如果微信小程序绑定了腾讯云账号，可以到腾讯云后台，把微信的关联解绑掉。
