### ISSUE TITLE
错误码5100，服务内部错误

### ISSUE THREAD

**Issue by triton2** [tencentyun/wafer2-startup#7]
今天尝试搭建了一下，搞不定搞不定。。。

console报这个
"{"code":-1,"error":"ERR_GET_SESSION_KEY\n{\"code\":5100,\"message\":\"(-1)服务内部错误，请稍后重试或联系客服人员解决。\",\"codeDesc\":\"ResourceOpFailed\"}"}"

npm报这个
npm WARN koa-weapp-demo@1.0.0 No repository field.

然后吐槽一下，小程序的后端搭建资料简直太少了，搜不到。。。
问一下去哪里才能找到大佬问问题呢

**Comment by jas0ncn** [comment]
尝试点击“腾讯云”按钮，接着点击“重启服务”试试。

关于后端的资料，其实就是普通 Web 的后端设计
