### ISSUE TITLE
前端get请求带参数，后台的处理方法

### ISSUE THREAD

**Issue by HakChealKim** [tencentyun/wafer2-startup#71]
困扰了，两天了，
例如，前端的get 请求，＊＊＊.com/get？key=a;
这个路由要怎么弄？
后台怎样获得这个参数 key呢？

问题很低级，但希望得到大神的 一点点拨
![Uploading 屏幕快照 2017-10-28 下午8.44.22.png…]()

**Comment by HakChealKim** [comment]
![2017-10-28 8 44 22](https://user-images.githubusercontent.com/9987586/32134716-bb3f7ccc-bc25-11e7-8738-dcd58fc3b0c7.png)

**Comment by jas0ncn** [comment]
`ctx.query.key` 这样可以拿到 url 的 querystring
