### ISSUE TITLE
没有 npm run dev 的 script

### ISSUE THREAD

**Issue by Haixiang6123** [tencentyun/wafer2-startup#72]
在本地部署的时候，并没有readme中的npm run dev指令。

这个是readme里的教程
![image](https://user-images.githubusercontent.com/17061654/32155502-e75aa9ec-bcf4-11e7-99ac-ec9122beb9d4.png)

这个 server 里的 package.json
![image](https://user-images.githubusercontent.com/17061654/32155474-c302a18a-bcf4-11e7-86a7-08ee06fb2c45.png)

虽然我尝试了 npm run local-dev 但是都报错，好像是 es6 语法不能被识别。

![img_0836](https://user-images.githubusercontent.com/17061654/32155574-527c1f9e-bcf5-11e7-9211-c51defbaf5bd.JPG)

**Comment by jas0ncn** [comment]
您可以更新 Node.js 到大于 7.6 的版本，然后运行 npm run local-dev
