### ISSUE TITLE
本地开发图片上传问题

### ISSUE THREAD

**Issue by Haixiang6123** [tencentyun/wafer2-startup#73]
好像说的是找不到当前的图片
![qq 20171101112158](https://user-images.githubusercontent.com/17061654/32290314-f2a8a156-bef6-11e7-9e29-24f0925d0b9d.png)
控制台显示如下
![qq 20171101112411](https://user-images.githubusercontent.com/17061654/32290419-40256716-bef7-11e7-8509-7d3b5368b69d.png)

我用的是wafer2-startup node.js的例子

**Comment by jas0ncn** [comment]
![image](https://user-images.githubusercontent.com/3380894/32315912-1cc44f46-bf7c-11e7-9115-73a9529445ae.png)

显然，是本地的代码错误。你是在 windows 上本地运行的，请在 C 盘创建一个 tmp 文件夹并赋予权限，
