### ISSUE TITLE
上传腾讯云报错问题

### ISSUE THREAD

**Issue by Coderkobe** [tencentyun/wafer2-startup#74]
![image](https://user-images.githubusercontent.com/18484020/32306419-1c024560-bfb6-11e7-8c75-d95743be4de4.png)
![image](https://user-images.githubusercontent.com/18484020/32306441-3152b6b6-bfb6-11e7-8209-820a9daebff1.png)
执行完就报错了，也没有具体的报错信息。不好定位问题

**Comment by jas0ncn** [comment]
重新尝试一下
