### ISSUE TITLE
上传到腾讯云时报错10080

### ISSUE THREAD

**Issue by soulspoison** [tencentyun/wafer2-startup#75]
![image](https://user-images.githubusercontent.com/22145424/32318122-2f7c56fe-bff1-11e7-9675-3b5f3b3588a6.png)

**Comment by soulspoison** [comment]
按照流程，但之前就创建了小程序项目

**Comment by jas0ncn** [comment]
在 project.config.json 里面加上 "qcloudRoot": "./server"
