### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by HakChealKim** [tencentyun/wafer2-startup#76]
![2017-11-02 11 34 58](https://user-images.githubusercontent.com/9987586/32334912-a4788484-c026-11e7-88e9-ed59328de317.png)

加了这段代码后，就报错，删除修改也不行；
服务重启也不行。。。。。
纠结

**Comment by jas0ncn** [comment]
502是 Node.js 进程没启起来。是你的 js 代码写的有问题。检查你的 js 语法
