### ISSUE TITLE
自行部署后验证信息不一致

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-startup#77]
自行部署文档里提到，当访问一个不存在的路由时，比如http://你的域名/weapp/a，会提示502 Bad Gateway，但我按自行部署文档一模一样的部署，访问不存在的路由时却返回{"code":0,"data":{}}。

**Comment by jas0ncn** [comment]
502 是整个 Node.js 挂了才会 502。。。返回你说的这个 json 字符串是正确的
