### ISSUE TITLE
POST请求数据是XML格式的问题

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-startup#78]
小程序支付回调的数据是xml格式，但是我测试发现使用wafer2-startup实现的回调服务不能接收xml格式数据，要怎么处理？

**Comment by jas0ncn** [comment]
参考一下这个文件里的注释：https://github.com/tencentyun/wafer2-startup/blob/master/server/middlewares/bodyparser.js

**Comment by qszhu** [comment]
try this and parse xml as text:

https://github.com/koajs/bodyparser/issues/45#issuecomment-220234917
