### ISSUE TITLE
上传部署的时候总是超时报错

### ISSUE THREAD

**Issue by Dev-Simon-Chen** [tencentyun/wafer2-startup#8]
每次点击上传部署代码，对话框很快显示上传成功，但是一直卡在部署中，，过了10分钟左右跳出这个错误
{"code":-1,"reason":"任务超时"}，这个怎么解决

**Comment by ontheway1215** [comment]
我的也是这个问题，又重新上传了一次成功了，但是请求的地址报错
![image](https://user-images.githubusercontent.com/11936847/29905184-aaad768e-8e3f-11e7-88ff-374ff0439639.png)
且模拟窗口请求不到页面
![image](https://user-images.githubusercontent.com/11936847/29905214-d9a0eee4-8e3f-11e7-9f07-fb0133ded851.png)

**Comment by wozhizui** [comment]
我刚开始也是，后来用了那个简化版demo就好用了。

**Comment by SouthernBox** [comment]
目前只能关掉重试了。。。

**Comment by zozowind** [comment]
同样的问题，简化版也试了，也是超时

**Comment by Aierui** [comment]
我刚刚试了下，也遇到这个问题。提示超时。

是不是现在服务还不可用呀？

**Comment by zozowind** [comment]
又重新试了一次，ok了，建议第二次试的时候可以选择上传增量代码

**Comment by ontheway1215** [comment]
部署成功了😁
1.如果是mac用户的话需要在设置选项的代理设置里面勾选不使用任何代理，勾选后直连网络
2.需要在微信小程序后台设置中的开发设置增加，服务器域名中增加请求域名
![image](https://user-images.githubusercontent.com/11936847/29908223-e7a0eff4-8e52-11e7-91d2-64a1d26fe07c.png)
也就是腾讯云给你分配的那个
![image](https://user-images.githubusercontent.com/11936847/29908265-15fa08ae-8e53-11e7-9029-0cb33b18d0b1.png)

**Comment by Dev-Simon-Chen** [comment]
更新31号的版本开发工具这个部署问题解决了，，但是请求还是有问题，，一直内部服务错误

**Comment by Dev-Simon-Chen** [comment]
更新31号的版本开发工具这个部署问题解决了，，但是请求还是有问题，，一直报内部服务错误

**Comment by jas0ncn** [comment]
你好，点击“登录”提示“(-1) 服务内部错误，请稍后重试或联系客服人员解决。”的错误，可以按照如下方式排查问题：
1. 检查是否将 `client/config.js` 里的 `host` 修改为分配的开发环境域名
2. 重新点击“编译”小程序，点击登录重试
3. 点击“腾讯云”-“重启服务”，重启成功之后点击登录重试
如果以上方法均无法解决，可以将你的腾讯云账号 ID（可以在这查看[https://console.qcloud.com/developer](https://console.qcloud.com/developer)）贴给我，我这里帮您排查一下。

**Comment by 17316226495** [comment]
已更新31号的版本开发工具 代码上传成功，部署没成功弹出 -80076 前两次都是{"code":-1,"reason":"任务超时"}

**Comment by jas0ncn** [comment]
重试一下看看。

**Comment by BraveZhang** [comment]
请问【腾讯云】-【安装依赖项】后报如下错误是什么原因：
 {"code":-1,
 "reason":
 "npm WARN checkPermissions Missing write access to /data/release/node-weapp-demo/node_modules/arr-flatten 
 npm WARN checkPermissions Missing write access to /data/release/node-weapp-demo/node_modules/ar
 "}

**Comment by Aierui** [comment]
这个问题可以解决吗？太恐怖了。。。开启后电脑直接发烧，卡

<img width="1272" alt="what" src="https://user-images.githubusercontent.com/16207137/29925736-dbfc5e2c-8e93-11e7-8856-47d56a79f501.png">

**Comment by jas0ncn** [comment]
@Aierui 我这边不是微信的哈~你可以去[微信开发者社区](https://developers.weixin.qq.com/)反馈一下。

**Comment by jas0ncn** [comment]
@BraveZhang 是开发环境吗？重新安装依赖呢？

**Comment by Aierui** [comment]
@jas0ncn 好的好的，感谢感谢。

**Comment by BraveZhang** [comment]
@jas0ncn 重新安装依赖搞定了，但是在代码上传测试代码进行部署的时候报如下错误：
{"code":-1,"reason":"module.js:487\n throw err;\n ^\n\nError: Cannot find module 'wafer-node-sdk'\n at Function.Module._resolveFilename (module.js:485:15)\n at Function.Module._load (module.js:437:25)\n at Module."}

**Comment by jas0ncn** [comment]
@BraveZhang 你这个错误就是没有安装依赖。。尝试重新安装依赖
