### ISSUE TITLE
自动登录失败

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-startup#80]
小程序里面有一个post请求，使用了自动登录，代码如下：
qcloud.request({
            login: true,
            url: config.service.doorUrl,
            data: { item: "something" },
            method: 'POST',
            header: {
                'content-type': 'application/json'
            },
            success: function (res) {
                //...
            },
            fail: function (res) {
                //...
            }
        });
业务服务器实现代码如下：
router.post('/door', validationMiddleware, controllers.door)
module.exports = async (ctx, next) => {
    if ('$wxInfo' in ctx.state && ctx.state.$wxInfo.loginState === 1) {
        // loginState 为 1，登录态校验成功
        var userInfo = ctx.state.$wxInfo.userinfo
        var doorreq = ctx.request.body
        //...
    } else {
        console.log('door request login state fail')
        ctx.body = {
            status: -1,
            msg: 'door request login state fail'
        }
    }
}
在测试的过程中发现，会出现loginState为0的情况（原因未知），只要出现这样情况，小程序客户端就必须删除重新进入才能登录成功。

**Comment by yuzifu** [comment]
好像是登录有效期是2小时，2小时后，小程序使用qcloud.rquest({login: true})请求，sdk里虽然会使用wx.checkSession进行会话检查，但返回的结果是有效的，所以不会再次登录。而业务服务器里$wxInfo.loginState已经为0了。出现这个问题是我使用方式不对吗？

**Comment by yuzifu** [comment]
已经确认，业务服务器这边登录状态有效期为2小时，2小时过后，loginState为0，而小程序这边wx.checkSession却依然返回true，造成此问题。

**Comment by jas0ncn** [comment]
并不需要调用 wx.checksession，checksession 返回的状态和登录态没有任何关系，登录态是单独颁发的，客户端在开发的时候应该考虑登录态过期之后重新进行登录。

**Comment by yuzifu** [comment]
wx.checksession是小程序里的SDK调用了，不是我自己写的

**Comment by jas0ncn** [comment]
OK，你更新一下最新的代码。已经修改了。

**Comment by jas0ncn** [comment]
升级支持新版本的时候忘记修改旧版本的逻辑啦~
