### ISSUE TITLE
fail url not in domain list(发布体验版)

### ISSUE THREAD

**Issue by HakChealKim** [tencentyun/wafer2-startup#81]
小程序开发环境测试OK后，发布了体验版；
就报以上错误
![wechatimg1](https://user-images.githubusercontent.com/9987586/32478161-0f22be54-c3be-11e7-9c8f-732f112c9b5a.jpeg)
![wechatimg2](https://user-images.githubusercontent.com/9987586/32478163-0f8c09fe-c3be-11e7-9bd7-9454aea04b09.jpeg)

**Comment by jas0ncn** [comment]
需要把请求的域名添加到微信小程序后台的安全域名中哈~
