### ISSUE TITLE
cos的配置是不是有问题？没有cn-south的map啊

### ISSUE THREAD

**Issue by bfkkkd** [tencentyun/wafer2-startup#84]

**Comment by bfkkkd** [comment]
按照说明换了 ap-guangzhou 后还是不行，提示403

提示403，还需要别的权限？
VM2095:2 Failed to load image http://wximg-1254136895.cosgz.myqcloud.com/1511873262825-BkPxiR5lf.png
the server responded with a status of 403 (HTTP/1.1 403 Forbidden)
From server 14.119.113.163

**Comment by bfkkkd** [comment]
uploader有两个问题， sign没取，无法显示。。 uploadfolder设置无效。。。

**Comment by bfkkkd** [comment]
sign的问题原来是在控制台设置成公开。。

**Comment by jas0ncn** [comment]
首先这个 bucket 需要是公有读私有写的。另外 uploadfolder 需要提前建好。

**Comment by bfkkkd** [comment]
看了下代码，uploadfolder 是因为返回的连接中没有加上？
imgUrl: `http://${config.cos.fileBucket}-${config.qcloudAppId}.cos${regionMap[config.cos.region]}.myqcloud.com/${imgKey}`,

**Comment by jas0ncn** [comment]
感谢提醒！上传应该是成功的吧？这里我加上

**Comment by bfkkkd** [comment]
上传是没问题的

**Comment by jas0ncn** [comment]
好的，感谢提醒，下个版本修复。你可以先手动处理一下~
