### ISSUE TITLE
能不能提供连接数据更详细的例子，总是取不出数据啊

### ISSUE THREAD

**Issue by jacksplwxy** [tencentyun/wafer2-startup#87]
参考的[文档](https://github.com/tencentyun/wafer2-startup/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF-sdk-%E8%BF%9E%E6%8E%A5%E5%92%8C%E6%93%8D%E4%BD%9C%E6%95%B0%E6%8D%AE%E5%BA%93)，但还是取不出数据，代码如下：
const qcloud = require('../qcloud.js')
module.exports = async (ctx, next) => {
  if (ctx.state.$wxInfo.loginState === 1) {
    const { mysql } = qcloud
    let result=mysql('question_sort').select('*').where({ id: 1 })
    ctx.state.data = result
  } else {
    ctx.state.code = -1
  }
}

**Comment by jas0ncn** [comment]
mysql的查询全都是异步的，要 await mysql()
