### ISSUE TITLE
{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}.

### ISSUE THREAD

**Issue by marcous1987** [tencentyun/wafer2-startup#89]
你好, 我上传测试代码时, 总是提示如下错误:
{"code":-1,"reason":"6001:主机未找到或者不在您账户下"}.
麻烦您抽时间处理一下这个问题, 万分感谢!!
注册账号:gh_d9917ba67b6d(微信公众平台账号)
账号ID :100003206396
APPID :1255677777

**Comment by jas0ncn** [comment]
您好，您的这个问题解决了吗？

**Comment by marcous1987** [comment]
已解决  谢谢
