### ISSUE TITLE
小程序chat有两个bug

### ISSUE THREAD

**Issue by idleb** [tencentyun/wafer2-startup#90]
/client/pages/chat/chat.js 
209 行：if (this.tunnel.isClosed())。Android手机在chat页长时间关闭屏幕，this.tunnel 可能会被GC回收，再打开屏幕后，执行 sendmassage 会报错 this.tunnel 为 undefined。建议添加undefined条件：if (!this.tunnel || this.tunnel.isClosed())
111行：var tunnel = this.tunnel = new qcloud.Tunnel(config.service.tunnelUrl);小程序在开关屏幕频繁触发onShow和onHide时。有可能tunnel没有完全退出仍然是alived的状态，这里会报tunnel已存在的错误。建议提前检测this.tunnel 状态：if (this.tunnel && this.tunnel.isActive()) return;

**Comment by jas0ncn** [comment]
了解，这里我来看一下你说的这两个问题，你也可以提交 PR 帮忙修改这个问题，感谢提醒！
