### ISSUE TITLE
建议开放支持小程序服务端上传的代码功能！

### ISSUE THREAD

**Issue by cmideal** [tencentyun/wafer2-startup#92]
新版小程序解决方案目前暂无计划支持开发服务器连接能力，你只能通过微信开发者工具上传、部署、调试代码。

看到这个我觉得，新版工具已经支持本地调用http接口，虽然我们可以模拟登录方式，但是这样确实很麻烦，建议腾讯云这边可以制作一个直接代码压缩包上传的后端接口，现在我们就是用腾讯云，但是客户多了起来，真的一个个的给开工具，特别麻烦。更新不及时。

**Comment by jas0ncn** [comment]
不是很清楚您的需求？一个个开的意思是？

**Comment by cmideal** [comment]
现在小程序web开发工具已经支持了http方式。这个不清楚是不是你们这边做的。
我的建议是：
第一种解决方案
1:开发登录检查
2:退出logout功能
3:获取二维码后，可以有接口可以查询是否登录成功。
4:获取打开文件目录的正确与否
5:有接口可以获取上传是否成功，如果有错误可以提示错误。

第二种：
服务端直接可以直接操作以上这些，我们自己打包文件，然后上传文件到小程序服务器

**Comment by jas0ncn** [comment]
我们只是提供腾讯云方面的支持哈，你说的这个是微信的，我也不清楚哦
