### ISSUE TITLE
按照wiki自行部署的文档部署后信道服务出现的问题及个人解决方法

### ISSUE THREAD

**Issue by naivenan** [tencentyun/wafer2-startup#94]
wiki自行部署的文档中：
上传 Demo 和启动
到 Wafer2-startup 仓库下载最新的 Demo 代码，修改 server/config.js：
这个地方

config.js文件里的tunnelServerUrl原文是http://tunnel.ws.qcloud.la，

问题：
按照原文配置后，使用开发工具测试时发现可以连接信道服务但是无法推送消息，
在调试器network中发现推送消息后信道服务器回复receiveUrl fail，
经过查看sdk代码发现这个receive是拼接而成，协议名是取自配置文件的tunnelServerUrl的协议，即http
但是小程序和后台的数据交互都是基于https的，因此消息推送失败了。

我个人的解决方法：
将/server/config.js的tunnelServerUrl配置为https://tunnel.ws.qcloud.la，即http改为https
经测试后可以正常使用信道服务。

建议：
文档中加上注释补充说明需要根据情况修改此协议，或者直接配置成https。

诉苦：
原来使用wafer2的一站式部署开发环境是不允许外网访问服务器的，单步调试也没法看到配置文件，
因此不知道是怎么配置的，但是想换到自己的服务器上时就出现了这个问题，苦苦调试了两天无果。
最后静下心来看信道服务文档以及wafer-node-sdk源码才一步步发现问题所在。
希望能稍微帮到和我遇到同样问题的朋友TAT

**Comment by jas0ncn** [comment]
感谢提醒，已经修改文档了。

**Comment by Bluebang** [comment]
呵呵，原文还是一样的问题，你们写的文档简直跟shi一样。
