### ISSUE TITLE
tnpm 是是什么怎么安装？

### ISSUE THREAD

**Issue by yishuiliunian** [tencentyun/wafer2-startup#97]
在README.md 中有一段

~~
# 开发环境，监听文件变化自动重启，并会输出 debug 信息
tnpm run dev

# 线上部署环境
tnpm start
~~

我使用npm 安装了tnpm

~~~
npm install tnpm -g
~~~

运行报错：

~~~
 tnpm run dev
This is a fake package on official npm.
Perhaps you installed the wrong one.
Please visit urls below and use the right way to install tnpm
A1ib4b4: http://t.cn/Rysxjww
T3nC3nt: http://km.oa.com/articles/show/260990
~~~

**Comment by jas0ncn** [comment]
额，不好意思，这里是因为写错了。直接使用 npm 安装即可。

**Comment by shuguangzhang1985** [comment]
安装了tnpm后，运行tnpm -v 一直提示 
This is a fake package on official npm.
Perhaps you installed the wrong one.
Please visit urls below and use the right way to install tnpm
A1ib4b4: http://t.cn/Rysxjww
T3nC3nt: http://km.oa.com/articles/show/260990
哪里出的问题？？

**Comment by jas0ncn** [comment]
@shuguangzhang1985 tnpm 是腾讯内部使用的一个内网 npm 版本，外部直接使用 npm 即可。
