### ISSUE TITLE
自行布署时域名解析不工作

### ISSUE THREAD

**Issue by superupon** [tencentyun/wafer2-startup#99]
我是按照这篇文档在腾讯的云服务器上进行配置的，
https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2

域名是自动生成的，91039621.qcloud.la
通过点击文档上的链接，下载证书到服务器的/data/release/nginx下， 配置完成后，我用nginx -t 结果也是成功的，但是我用nginx启动后，通过域名访问时，返回Dial Timeout, 域名解析不了。

**Comment by jas0ncn** [comment]
自行部署需要自己的域名哈。qcloud.la 的域名在我们这里，没有办法解析到你的服务器上。
